import type { MacroTotals, Recommendation } from "@/lib/types";

export type FoodCatalogScene =
  | "fast_food"
  | "hotpot"
  | "tea_coffee"
  | "convenience"
  | "local_meal"
  | "light_meal"
  | "fruit_snack"
  | "supplement";

export type FoodCatalogItem = {
  id: string;
  brand: string;
  title: string;
  scene: FoodCatalogScene;
  foodType: string;
  category: Recommendation["category"];
  items: string[];
  macros: MacroTotals;
  note: string;
  caution?: string;
  aliases: string[];
  goalFit: Array<"muscle" | "fat_loss" | "weight_loss" | "health">;
  lightOnly?: boolean;
};

export const foodCatalog: FoodCatalogItem[] = [
  {
    id: "cat-mcd-grilled-burger-apple",
    brand: "麦当劳",
    title: "板烧鸡腿堡 + 苹果片 + 无糖茶",
    scene: "fast_food",
    foodType: "汉堡轻套餐",
    category: "topup",
    items: ["板烧鸡腿堡", "苹果片", "无糖茶"],
    macros: { protein: 28, carbs: 48, fat: 16, calories: 455, fiber: 5 },
    note: "想吃汉堡但今天快达标时，用水果替代薯条会更稳。",
    aliases: ["麦当劳", "板烧鸡腿堡", "麦记", "汉堡"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-mcd-bigmac-fries",
    brand: "麦当劳",
    title: "巨无霸 + 中薯 + 无糖可乐",
    scene: "fast_food",
    foodType: "汉堡套餐",
    category: "meal",
    items: ["巨无霸", "中薯", "无糖可乐"],
    macros: { protein: 30, carbs: 84, fat: 45, calories: 900, fiber: 7 },
    note: "缺口很大、训练日想快乐吃时可用，下一餐要清淡一点。",
    caution: "脂肪偏高，减脂和减重用户不建议频繁选。",
    aliases: ["麦当劳", "巨无霸", "薯条", "big mac"],
    goalFit: ["muscle"]
  },
  {
    id: "cat-kfc-spicy-burger-corn",
    brand: "肯德基",
    title: "香辣鸡腿堡 + 玉米杯",
    scene: "fast_food",
    foodType: "汉堡轻套餐",
    category: "topup",
    items: ["香辣鸡腿堡", "玉米杯", "无糖茶"],
    macros: { protein: 24, carbs: 52, fat: 18, calories: 470, fiber: 5 },
    note: "比加薯条更适合补一点碳水和蛋白，适合两顿饭后的轻补。",
    aliases: ["肯德基", "kfc", "香辣鸡腿堡", "玉米杯"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-kfc-protein-box",
    brand: "肯德基",
    title: "原味鸡 + 鸡胸肉卷 + 蔬菜杯",
    scene: "fast_food",
    foodType: "高蛋白快餐",
    category: "meal",
    items: ["原味鸡 1 块", "鸡胸肉卷", "蔬菜杯"],
    macros: { protein: 52, carbs: 48, fat: 30, calories: 680, fiber: 6 },
    note: "训练日缺蛋白时比较快，适合不想等正餐外卖的时候。",
    caution: "炸鸡皮会明显增加脂肪，可以去掉一部分皮。",
    aliases: ["肯德基", "kfc", "原味鸡", "鸡肉卷"],
    goalFit: ["muscle", "fat_loss"]
  },
  {
    id: "cat-burgerking-whopper-jr",
    brand: "汉堡王",
    title: "皇堡 Jr. + 烤鸡块",
    scene: "fast_food",
    foodType: "汉堡轻套餐",
    category: "topup",
    items: ["皇堡 Jr.", "烤鸡块 6 块", "无糖饮料"],
    macros: { protein: 42, carbs: 45, fat: 28, calories: 600, fiber: 4 },
    note: "比大份皇堡套餐更好控量，适合缺蛋白但不想太撑。",
    aliases: ["汉堡王", "皇堡", "烤鸡块", "burger king"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-tastien-chicken-burger",
    brand: "塔斯汀",
    title: "中国汉堡 + 鸡肉小食 + 无糖茶",
    scene: "fast_food",
    foodType: "中式汉堡套餐",
    category: "meal",
    items: ["鸡腿中国汉堡", "鸡肉小食", "无糖茶"],
    macros: { protein: 44, carbs: 70, fat: 32, calories: 760, fiber: 5 },
    note: "门店多、执行成本低，训练日缺口较大时可以作为正餐。",
    caution: "酱料和炸物会让脂肪上来，减重用户少加酱。",
    aliases: ["塔斯汀", "中国汉堡", "汉堡"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-dicos-rice-chicken",
    brand: "德克士",
    title: "脆皮鸡腿饭 + 蔬菜汤",
    scene: "fast_food",
    foodType: "快餐饭",
    category: "meal",
    items: ["脆皮鸡腿饭", "蔬菜汤"],
    macros: { protein: 38, carbs: 82, fat: 28, calories: 735, fiber: 6 },
    note: "比只吃炸鸡更像一顿完整饭，碳水和蛋白都能补。",
    caution: "鸡腿皮和酱汁会提高脂肪。",
    aliases: ["德克士", "鸡腿饭", "快餐饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-subway-tuna-six",
    brand: "赛百味",
    title: "金枪鱼 6 寸 + 蔬菜加量",
    scene: "fast_food",
    foodType: "三明治",
    category: "topup",
    items: ["金枪鱼 6 寸", "生菜番茄加量", "不加甜酱"],
    macros: { protein: 28, carbs: 46, fat: 15, calories: 430, fiber: 7 },
    note: "轻一点的连锁方案，适合补碳水、蛋白和纤维。",
    aliases: ["赛百味", "subway", "金枪鱼", "三明治"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-pizza-hut-salad-slice",
    brand: "必胜客",
    title: "薄底披萨 2 片 + 鸡胸沙拉",
    scene: "fast_food",
    foodType: "披萨轻配",
    category: "meal",
    items: ["薄底披萨 2 片", "鸡胸沙拉", "无糖饮料"],
    macros: { protein: 38, carbs: 58, fat: 24, calories: 610, fiber: 7 },
    note: "想吃披萨时用沙拉把蛋白和纤维补上，比整张披萨更可控。",
    aliases: ["必胜客", "披萨", "pizza"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hdl-lean-hotpot",
    brand: "海底捞",
    title: "番茄锅牛肉虾滑配菜",
    scene: "hotpot",
    foodType: "火锅高蛋白",
    category: "meal",
    items: ["番茄锅", "牛肉片 150g", "虾滑半份", "生菜", "金针菇"],
    macros: { protein: 58, carbs: 28, fat: 36, calories: 670, fiber: 8 },
    note: "火锅也可以吃得像训练餐，关键是锅底、蘸料和主食份量。",
    caution: "麻酱、油碟和酥肉会把脂肪拉高。",
    aliases: ["海底捞", "火锅", "番茄锅", "虾滑", "牛肉片"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-hdl-light-mix",
    brand: "海底捞",
    title: "毛肚豆腐蔬菜轻补",
    scene: "hotpot",
    foodType: "火锅轻加餐",
    category: "topup",
    items: ["毛肚半份", "豆腐半份", "菠菜", "娃娃菜", "菌菇"],
    macros: { protein: 30, carbs: 22, fat: 12, calories: 330, fiber: 9 },
    note: "两顿正餐后还差一点蛋白和纤维时，可以吃这个，不用再点一顿大夜宵。",
    aliases: ["海底捞", "毛肚", "豆腐", "蔬菜", "火锅"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-banu-beef-mushroom",
    brand: "巴奴毛肚火锅",
    title: "毛肚 + 牛肉 + 菌菇蔬菜",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["毛肚", "牛肉", "菌菇拼盘", "蔬菜拼盘", "清汤或番茄锅"],
    macros: { protein: 56, carbs: 30, fat: 34, calories: 650, fiber: 10 },
    note: "适合想吃火锅但又想控制碳水的人，蘸料别用太多油。",
    caution: "油碟和麻酱是热量大头。",
    aliases: ["巴奴", "毛肚", "火锅", "牛肉"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-xiabu-personal-hotpot",
    brand: "呷哺呷哺",
    title: "单人清汤肥牛蔬菜锅",
    scene: "hotpot",
    foodType: "单人火锅",
    category: "meal",
    items: ["清汤锅", "肥牛", "豆腐", "青菜", "半碗米饭"],
    macros: { protein: 44, carbs: 45, fat: 28, calories: 610, fiber: 8 },
    note: "单人火锅比较容易控量，适合晚餐想吃热乎一点。",
    caution: "沙茶酱和麻酱少放。",
    aliases: ["呷哺呷哺", "单人火锅", "肥牛"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-luckin-latte-yogurt",
    brand: "瑞幸 / 便利店",
    title: "无糖拿铁 + 希腊酸奶",
    scene: "tea_coffee",
    foodType: "咖啡加餐",
    category: "topup",
    items: ["无糖拿铁", "希腊酸奶 1 杯"],
    macros: { protein: 22, carbs: 18, fat: 8, calories: 245, fiber: 0 },
    note: "下午差一点蛋白质时很顺手，不用再点一顿正餐。",
    aliases: ["瑞幸", "拿铁", "酸奶", "咖啡"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-starbucks-oat-latte-egg",
    brand: "星巴克 / 便利店",
    title: "燕麦拿铁 + 茶叶蛋",
    scene: "tea_coffee",
    foodType: "咖啡加餐",
    category: "topup",
    items: ["中杯燕麦拿铁", "茶叶蛋 1 个"],
    macros: { protein: 14, carbs: 28, fat: 9, calories: 250, fiber: 2 },
    note: "想喝咖啡又差一点蛋白时，配个蛋比只喝甜咖啡更稳。",
    aliases: ["星巴克", "燕麦拿铁", "茶叶蛋", "咖啡"],
    goalFit: ["health", "fat_loss", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-heytea-light",
    brand: "喜茶 / 奈雪",
    title: "清爽茶饮 + 小蛋白加餐",
    scene: "tea_coffee",
    foodType: "茶饮配置",
    category: "topup",
    items: ["无糖茶底", "少量仙草", "茶叶蛋或酸奶"],
    macros: { protein: 14, carbs: 24, fat: 6, calories: 210, fiber: 3 },
    note: "想喝饮品时，茶底、少糖、少小料，再配一点蛋白。",
    aliases: ["喜茶", "奈雪", "奶茶", "水果茶", "仙草"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-chagee-low-sugar",
    brand: "霸王茶姬",
    title: "伯牙绝弦少糖版",
    scene: "tea_coffee",
    foodType: "奶茶配置",
    category: "snack",
    items: ["中杯原叶鲜奶茶", "少糖", "不加额外小料"],
    macros: { protein: 8, carbs: 34, fat: 8, calories: 240, fiber: 0 },
    note: "想喝奶茶时用少糖、不要小料，热量会比奶盖和珍珠款更可控。",
    caution: "减重用户把它当偶尔快乐，不要每天用奶茶补碳水。",
    aliases: ["霸王茶姬", "伯牙绝弦", "奶茶", "少糖"],
    goalFit: ["health"],
    lightOnly: true
  },
  {
    id: "cat-mixue-lemon-egg",
    brand: "蜜雪冰城 / 便利店",
    title: "少糖柠檬水 + 茶叶蛋",
    scene: "tea_coffee",
    foodType: "饮品加餐",
    category: "topup",
    items: ["少糖柠檬水", "茶叶蛋 1 个"],
    macros: { protein: 8, carbs: 26, fat: 5, calories: 180, fiber: 1 },
    note: "想喝点甜的可以这样配，热量轻一点，也能顺手补一点蛋白。",
    aliases: ["蜜雪冰城", "柠檬水", "茶叶蛋"],
    goalFit: ["health", "fat_loss", "weight_loss"],
    lightOnly: true
  },
  {
    id: "cat-guming-fruit-tea-yogurt",
    brand: "古茗 / 便利店",
    title: "水果茶少糖 + 无糖酸奶",
    scene: "tea_coffee",
    foodType: "水果茶加餐",
    category: "topup",
    items: ["少糖水果茶", "无糖酸奶 1 杯"],
    macros: { protein: 10, carbs: 38, fat: 4, calories: 230, fiber: 3 },
    note: "水果茶主要补碳水，配酸奶能让加餐更完整一点。",
    aliases: ["古茗", "水果茶", "酸奶", "奶茶"],
    goalFit: ["health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-chabaidao-light",
    brand: "茶百道",
    title: "纯茶少糖 + 鸡胸肉肠",
    scene: "tea_coffee",
    foodType: "茶饮加餐",
    category: "topup",
    items: ["纯茶或水果茶少糖", "鸡胸肉肠 1 根"],
    macros: { protein: 14, carbs: 24, fat: 5, calories: 195, fiber: 1 },
    note: "想喝茶饮但蛋白还差一点，用鸡胸肉肠兜底。",
    aliases: ["茶百道", "纯茶", "水果茶", "鸡胸肉肠"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-familymart-chicken-riceball",
    brand: "全家便利店",
    title: "即食鸡胸肉 + 饭团 + 蔬菜汁",
    scene: "convenience",
    foodType: "便利店训练餐",
    category: "topup",
    items: ["即食鸡胸肉", "饭团", "无糖蔬菜汁"],
    macros: { protein: 36, carbs: 44, fat: 8, calories: 390, fiber: 5 },
    note: "便利店也能吃得像样，适合训练后但不想等外卖。",
    aliases: ["全家", "便利店", "鸡胸肉", "饭团"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-lawson-oat-egg",
    brand: "罗森",
    title: "燕麦杯 + 茶叶蛋 + 无糖豆浆",
    scene: "convenience",
    foodType: "便利店早餐",
    category: "topup",
    items: ["燕麦杯", "茶叶蛋", "无糖豆浆"],
    macros: { protein: 24, carbs: 46, fat: 12, calories: 390, fiber: 7 },
    note: "早餐或晚间轻补都合适，蛋白、碳水和纤维比较均衡。",
    aliases: ["罗森", "燕麦", "茶叶蛋", "豆浆", "便利店"],
    goalFit: ["health", "fat_loss", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-711-oden-riceball",
    brand: "711",
    title: "关东煮牛肉丸 + 蔬菜 + 饭团",
    scene: "convenience",
    foodType: "便利店组合",
    category: "snack",
    items: ["牛肉丸 4 个", "蔬菜拼盘", "饭团"],
    macros: { protein: 35, carbs: 45, fat: 18, calories: 520, fiber: 8 },
    note: "轻一点的便利店方案，适合不想吃太撑的时候。",
    aliases: ["711", "关东煮", "饭团", "便利店"],
    goalFit: ["muscle", "health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-convenience-veggie-sausage",
    brand: "便利店加餐",
    title: "蔬菜杯 + 鸡胸肉肠",
    scene: "convenience",
    foodType: "轻加餐",
    category: "topup",
    items: ["蔬菜杯", "鸡胸肉肠 1 根"],
    macros: { protein: 16, carbs: 14, fat: 5, calories: 165, fiber: 6 },
    note: "纤维差一点、蛋白质也差一点时很合适。",
    aliases: ["便利店", "蔬菜杯", "鸡胸肉肠"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-laoxiangji-chicken-rice",
    brand: "老乡鸡",
    title: "葱油鸡腿饭 + 青菜 + 汤",
    scene: "local_meal",
    foodType: "中式快餐",
    category: "meal",
    items: ["鸡腿饭", "青菜", "清汤"],
    macros: { protein: 46, carbs: 78, fat: 24, calories: 710, fiber: 7 },
    note: "中式快餐里比较完整的一顿，适合训练日正常吃饭。",
    aliases: ["老乡鸡", "鸡腿饭", "中式快餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-shaxian-chicken-egg",
    brand: "沙县小吃",
    title: "鸡腿饭 + 卤蛋 + 青菜",
    scene: "local_meal",
    foodType: "中式快餐",
    category: "meal",
    items: ["鸡腿饭", "卤蛋", "青菜"],
    macros: { protein: 48, carbs: 55, fat: 32, calories: 700, fiber: 7 },
    note: "外卖里比较朴素的一档，碳水和蛋白质都好补。",
    aliases: ["沙县", "鸡腿饭", "卤蛋", "小吃"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-lanzhou-beef-noodle",
    brand: "兰州牛肉面",
    title: "清汤牛肉面 + 加牛肉 + 青菜",
    scene: "local_meal",
    foodType: "粉面",
    category: "meal",
    items: ["牛肉面", "加牛肉", "青菜"],
    macros: { protein: 42, carbs: 86, fat: 14, calories: 650, fiber: 6 },
    note: "训练日缺碳水又想吃热汤面时合适，加牛肉能补蛋白。",
    aliases: ["兰州拉面", "牛肉面", "面馆"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-yangguofu-malatang",
    brand: "杨国福 / 张亮麻辣烫",
    title: "麻辣烫高蛋白低油碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["牛肉片", "豆腐", "青菜", "菌菇", "少粉少麻酱"],
    macros: { protein: 40, carbs: 46, fat: 24, calories: 590, fiber: 10 },
    note: "麻辣烫可以很灵活，少粉、少麻酱，多肉和蔬菜会更适合减脂。",
    caution: "麻酱、方便面和丸子会明显增加热量。",
    aliases: ["杨国福", "张亮", "麻辣烫", "冒菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-huangmenji",
    brand: "黄焖鸡米饭",
    title: "黄焖鸡小份 + 半份米饭 + 青菜",
    scene: "local_meal",
    foodType: "盖饭",
    category: "meal",
    items: ["黄焖鸡小份", "半份米饭", "青菜"],
    macros: { protein: 38, carbs: 64, fat: 26, calories: 650, fiber: 6 },
    note: "想吃盖饭时把米饭减半、加青菜，整体更可控。",
    caution: "汤汁拌饭会让热量更高。",
    aliases: ["黄焖鸡", "米饭", "盖饭"],
    goalFit: ["health", "fat_loss", "muscle"]
  },
  {
    id: "cat-luojiang-pork-rice",
    brand: "隆江猪脚饭",
    title: "瘦肉拼青菜 + 半份饭",
    scene: "local_meal",
    foodType: "卤味饭",
    category: "meal",
    items: ["瘦肉或鸡腿", "青菜", "半份米饭", "少卤汁"],
    macros: { protein: 42, carbs: 58, fat: 30, calories: 675, fiber: 6 },
    note: "猪脚饭也能控，关键是少皮、少卤汁、加青菜。",
    caution: "肥肉和卤汁会显著提高脂肪和钠。",
    aliases: ["猪脚饭", "隆江", "卤味饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-canton-roast",
    brand: "烧腊饭",
    title: "白切鸡/叉烧双拼 + 青菜 + 半份饭",
    scene: "local_meal",
    foodType: "烧腊饭",
    category: "meal",
    items: ["白切鸡", "叉烧少量", "青菜", "半份饭"],
    macros: { protein: 45, carbs: 58, fat: 28, calories: 665, fiber: 6 },
    note: "烧腊饭选白切鸡、少酱汁，比全叉烧或烧鸭更稳。",
    caution: "烧鸭皮和甜酱汁热量较高。",
    aliases: ["烧腊", "白切鸡", "叉烧", "烧鸭饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-xiang-quick-stir",
    brand: "湘菜小炒",
    title: "小炒黄牛肉 + 青菜 + 半份饭",
    scene: "local_meal",
    foodType: "现炒快餐",
    category: "meal",
    items: ["小炒黄牛肉", "清炒青菜", "半份米饭"],
    macros: { protein: 46, carbs: 58, fat: 32, calories: 700, fiber: 8 },
    note: "现炒快餐很常见，少油、半份饭、加青菜会更适合训练和减脂。",
    caution: "重油重辣会让脂肪和钠偏高。",
    aliases: ["湘菜", "小炒黄牛肉", "现炒快餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-japanese-sushi-light",
    brand: "日料轻食",
    title: "三文鱼寿司 + 味增汤",
    scene: "light_meal",
    foodType: "日料轻食",
    category: "topup",
    items: ["三文鱼寿司 4 贯", "味增汤", "海藻小菜"],
    macros: { protein: 22, carbs: 40, fat: 10, calories: 340, fiber: 3 },
    note: "两顿正餐后还想吃点像样的，这种比大份盖饭更轻。",
    aliases: ["寿司", "三文鱼", "日料", "轻食"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-poke-small",
    brand: "轻食行业平均",
    title: "小份波奇碗",
    scene: "light_meal",
    foodType: "轻食碗",
    category: "topup",
    items: ["金枪鱼或鸡胸", "半份糙米", "牛油果少量", "蔬菜加量"],
    macros: { protein: 32, carbs: 42, fat: 16, calories: 450, fiber: 8 },
    note: "补蛋白、纤维和一点碳水，适合不想吃油腻正餐的时候。",
    aliases: ["波奇", "poke", "轻食", "鸡胸", "糙米"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-salad-whey",
    brand: "轻食 / 蛋白粉",
    title: "鸡胸沙拉 + 蛋白粉 1 勺",
    scene: "light_meal",
    foodType: "高蛋白轻食",
    category: "protein",
    items: ["鸡胸肉沙拉", "蛋白粉 1 勺"],
    macros: { protein: 65, carbs: 15, fat: 12, calories: 430, fiber: 7 },
    note: "吃不下太多饭时优先保蛋白，碳水缺口可以晚点再补。",
    aliases: ["鸡胸沙拉", "蛋白粉", "轻食", "whey"],
    goalFit: ["muscle", "fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-oat-night",
    brand: "夜宵加餐",
    title: "燕麦杯 + 牛奶",
    scene: "light_meal",
    foodType: "夜间轻加餐",
    category: "snack",
    items: ["燕麦 40g", "牛奶 250ml"],
    macros: { protein: 15, carbs: 42, fat: 9, calories: 310, fiber: 5 },
    note: "夜里还饿但不想点外卖时，这个能补碳水、蛋白质和纤维。",
    aliases: ["燕麦", "牛奶", "夜宵", "加餐"],
    goalFit: ["muscle", "health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-banana-yogurt",
    brand: "水果加餐",
    title: "香蕉 + 蓝莓酸奶",
    scene: "fruit_snack",
    foodType: "水果酸奶",
    category: "topup",
    items: ["香蕉 1 根", "蓝莓一小盒", "无糖酸奶 1 杯"],
    macros: { protein: 13, carbs: 44, fat: 4, calories: 260, fiber: 7 },
    note: "如果今天纤维和碳水差一点，用水果和酸奶补比夜宵正餐舒服。",
    aliases: ["香蕉", "蓝莓", "酸奶", "水果"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-orange-egg",
    brand: "水果加餐",
    title: "橙子 + 茶叶蛋",
    scene: "fruit_snack",
    foodType: "水果蛋白",
    category: "topup",
    items: ["橙子 2 个", "茶叶蛋 1 个"],
    macros: { protein: 10, carbs: 32, fat: 6, calories: 220, fiber: 6 },
    note: "差一点纤维和蛋白质时很轻，晚饭后也不会太顶。",
    aliases: ["橙子", "茶叶蛋", "水果"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-apple-nuts",
    brand: "零食加餐",
    title: "苹果 + 坚果小包",
    scene: "fruit_snack",
    foodType: "坚果水果",
    category: "topup",
    items: ["苹果 1 个", "坚果 25g"],
    macros: { protein: 6, carbs: 30, fat: 15, calories: 270, fiber: 7 },
    note: "差一点热量、脂肪和纤维时很顺手，适合下午或夜里加餐。",
    aliases: ["苹果", "坚果", "零食", "水果"],
    goalFit: ["health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-beef-jerky-banana",
    brand: "零食加餐",
    title: "牛肉干 + 香蕉",
    scene: "fruit_snack",
    foodType: "零食蛋白",
    category: "topup",
    items: ["低糖牛肉干 35g", "香蕉 1 根"],
    macros: { protein: 18, carbs: 31, fat: 4, calories: 235, fiber: 3 },
    note: "蛋白和碳水都差一点时，用零食就能补，不需要大夜宵。",
    aliases: ["牛肉干", "香蕉", "零食"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-pork-jerky",
    brand: "零食加餐",
    title: "猪肉脯小包 + 无糖茶",
    scene: "fruit_snack",
    foodType: "零食蛋白",
    category: "topup",
    items: ["猪肉脯 35g", "无糖茶"],
    macros: { protein: 13, carbs: 12, fat: 4, calories: 140, fiber: 0 },
    note: "只差 10g 左右蛋白质时，用小零食补就够了。",
    caution: "钠可能偏高，别把它当每天固定方案。",
    aliases: ["猪肉脯", "零食", "无糖茶"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-whey-one-scoop",
    brand: "健身补剂",
    title: "蛋白粉 1 勺",
    scene: "supplement",
    foodType: "蛋白补剂",
    category: "protein",
    items: ["蛋白粉 1 勺", "水或无糖豆浆"],
    macros: { protein: 26, carbs: 4, fat: 2, calories: 140, fiber: 0 },
    note: "蛋白质差一点时最省事，尤其适合吃不下正餐的人。",
    aliases: ["蛋白粉", "whey", "乳清蛋白", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-casein-milk",
    brand: "健身补剂",
    title: "酪蛋白半勺 + 牛奶",
    scene: "supplement",
    foodType: "夜间蛋白",
    category: "protein",
    items: ["酪蛋白半勺", "低脂牛奶 250ml"],
    macros: { protein: 24, carbs: 14, fat: 5, calories: 200, fiber: 0 },
    note: "晚上只差一点蛋白质时，不用再点夜宵正餐。",
    aliases: ["酪蛋白", "牛奶", "蛋白粉", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-soy-milk-eggs",
    brand: "便利店 / 早餐店",
    title: "无糖豆浆 + 鸡蛋 2 个",
    scene: "supplement",
    foodType: "平价蛋白",
    category: "topup",
    items: ["无糖豆浆", "鸡蛋 2 个"],
    macros: { protein: 22, carbs: 12, fat: 12, calories: 245, fiber: 2 },
    note: "不用买补剂也能补蛋白，早餐、夜里都好执行。",
    aliases: ["豆浆", "鸡蛋", "早餐", "蛋白"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-breakfast-baozi-soymilk",
    brand: "早餐店",
    title: "肉包 2 个 + 无糖豆浆",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["肉包 2 个", "无糖豆浆 1 杯", "茶叶蛋 1 个"],
    macros: { protein: 28, carbs: 72, fat: 20, calories: 585, fiber: 4 },
    note: "很常见的上班早餐，加一个蛋能把蛋白补得更扎实。",
    aliases: ["包子", "豆浆", "茶叶蛋", "早餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-mantou-egg-hulatang",
    brand: "早餐店",
    title: "馒头 + 鸡蛋 + 胡辣汤",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["馒头 1 个", "鸡蛋 1 个", "胡辣汤 1 碗"],
    macros: { protein: 22, carbs: 68, fat: 14, calories: 490, fiber: 5 },
    note: "北方早餐高频组合，训练日可以多加一个蛋或牛肉。",
    aliases: ["馒头", "胡辣汤", "鸡蛋", "早餐"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-breakfast-wonton",
    brand: "早餐店",
    title: "鲜肉馄饨 + 茶叶蛋",
    scene: "local_meal",
    foodType: "馄饨",
    category: "meal",
    items: ["鲜肉馄饨 1 碗", "茶叶蛋 1 个", "青菜"],
    macros: { protein: 30, carbs: 58, fat: 16, calories: 500, fiber: 4 },
    note: "比单吃面包更完整，适合早餐或晚间不想太油的一餐。",
    aliases: ["馄饨", "云吞", "茶叶蛋", "早餐"],
    goalFit: ["health", "fat_loss", "muscle"]
  },
  {
    id: "cat-breakfast-noodle-egg",
    brand: "早餐面馆",
    title: "汤面 + 煎蛋 + 青菜",
    scene: "local_meal",
    foodType: "面条",
    category: "meal",
    items: ["汤面 1 碗", "煎蛋 1 个", "青菜加量"],
    macros: { protein: 24, carbs: 82, fat: 16, calories: 565, fiber: 5 },
    note: "面条是高频早餐，蛋白偏少时加蛋或牛肉会更稳。",
    aliases: ["面条", "汤面", "煎蛋", "早餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-jianbing",
    brand: "煎饼摊",
    title: "煎饼果子少酱版",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["煎饼果子", "加鸡蛋", "少薄脆", "少酱"],
    macros: { protein: 22, carbs: 66, fat: 20, calories: 535, fiber: 4 },
    note: "很常见也很好吃，少酱少薄脆能让热量更可控。",
    caution: "薄脆和甜面酱多了会让油脂和热量明显上升。",
    aliases: ["煎饼果子", "煎饼", "早餐", "鸡蛋"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-breakfast-egg-pancake",
    brand: "早餐摊",
    title: "鸡蛋灌饼 + 无糖豆浆",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["鸡蛋灌饼", "生菜", "无糖豆浆"],
    macros: { protein: 24, carbs: 62, fat: 24, calories: 560, fiber: 4 },
    note: "赶时间时很容易买到，少酱、加生菜会更适合日常。",
    caution: "饼皮油脂偏高，减重用户别天天吃。",
    aliases: ["鸡蛋灌饼", "豆浆", "早餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-porridge-youtiao",
    brand: "早餐店",
    title: "小米粥 + 油条半根 + 鸡蛋",
    scene: "local_meal",
    foodType: "粥类早餐",
    category: "meal",
    items: ["小米粥 1 碗", "油条半根", "鸡蛋 1 个", "小菜少量"],
    macros: { protein: 18, carbs: 58, fat: 17, calories: 455, fiber: 3 },
    note: "想吃油条也可以，把油条减半，再用鸡蛋补蛋白。",
    caution: "油条脂肪高，适合偶尔快乐一下。",
    aliases: ["粥", "油条", "鸡蛋", "早餐"],
    goalFit: ["health", "fat_loss"]
  },
  {
    id: "cat-breakfast-rice-roll",
    brand: "广式早餐",
    title: "鲜虾肠粉 + 鸡蛋",
    scene: "local_meal",
    foodType: "广式早餐",
    category: "meal",
    items: ["鲜虾肠粉", "鸡蛋 1 个", "少酱油"],
    macros: { protein: 26, carbs: 60, fat: 12, calories: 455, fiber: 2 },
    note: "华南常见早餐，脂肪不算高，但蛋白可以靠虾和鸡蛋补。",
    aliases: ["肠粉", "鲜虾肠粉", "广式早餐"],
    goalFit: ["health", "fat_loss", "muscle"]
  },
  {
    id: "cat-breakfast-xiaolongbao",
    brand: "早餐店",
    title: "小笼包 + 紫菜蛋花汤",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["小笼包 6 个", "紫菜蛋花汤"],
    macros: { protein: 26, carbs: 64, fat: 24, calories: 580, fiber: 3 },
    note: "常见早餐组合，汤里有蛋会比只吃包子更完整。",
    caution: "小笼包汤汁和肉馅脂肪不低。",
    aliases: ["小笼包", "蛋花汤", "早餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-reganmian",
    brand: "热干面店",
    title: "热干面小份 + 豆浆",
    scene: "local_meal",
    foodType: "武汉早餐",
    category: "meal",
    items: ["热干面小份", "无糖豆浆"],
    macros: { protein: 22, carbs: 86, fat: 24, calories: 650, fiber: 5 },
    note: "碳水很足，适合训练日前后；小份和无糖豆浆更好控。",
    caution: "芝麻酱较多时脂肪会明显上升。",
    aliases: ["热干面", "武汉早餐", "豆浆"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-dumpling-veg-egg",
    brand: "饺子馆",
    title: "白菜猪肉饺 + 紫菜蛋花汤",
    scene: "local_meal",
    foodType: "饺子",
    category: "meal",
    items: ["白菜猪肉饺 12 个", "紫菜蛋花汤"],
    macros: { protein: 34, carbs: 72, fat: 24, calories: 650, fiber: 5 },
    note: "饺子是很常见的正餐，配汤比再加炸物更稳。",
    aliases: ["饺子", "水饺", "蛋花汤"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-ziguangyuan-beef-rice",
    brand: "紫光园 / 中式快餐",
    title: "牛肉饭 + 拌青菜",
    scene: "local_meal",
    foodType: "中式快餐",
    category: "meal",
    items: ["牛肉饭", "拌青菜", "清汤"],
    macros: { protein: 44, carbs: 82, fat: 24, calories: 720, fiber: 7 },
    note: "午饭晚饭都容易执行，蛋白和碳水比较完整。",
    aliases: ["牛肉饭", "中式快餐", "青菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-stir-fry-tomato-egg-beef",
    brand: "家常炒菜",
    title: "番茄炒蛋 + 小炒牛肉 + 米饭",
    scene: "local_meal",
    foodType: "家常炒菜",
    category: "meal",
    items: ["番茄炒蛋", "小炒牛肉", "米饭 1 碗", "青菜"],
    macros: { protein: 50, carbs: 86, fat: 32, calories: 820, fiber: 8 },
    note: "典型中式午晚餐，训练日补得很完整。",
    caution: "外卖炒菜如果油多，脂肪会比估算更高。",
    aliases: ["炒菜", "番茄炒蛋", "小炒牛肉", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-stir-fry-chicken-broccoli",
    brand: "家常炒菜",
    title: "西兰花鸡胸 + 米饭",
    scene: "local_meal",
    foodType: "控脂炒菜",
    category: "meal",
    items: ["西兰花鸡胸", "米饭 1 碗", "菌菇汤"],
    macros: { protein: 48, carbs: 72, fat: 16, calories: 625, fiber: 10 },
    note: "更偏减脂和健康管理，蛋白和纤维都比较舒服。",
    aliases: ["西兰花", "鸡胸", "炒菜", "米饭"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-home-tomato-egg-rice",
    brand: "家常菜 / 自己做饭",
    title: "番茄炒蛋 + 米饭",
    scene: "local_meal",
    foodType: "家常菜",
    category: "meal",
    items: ["番茄炒蛋", "米饭 1 碗", "清炒青菜"],
    macros: { protein: 24, carbs: 82, fat: 22, calories: 625, fiber: 7 },
    note: "最容易做的一顿家常饭，鸡蛋补蛋白，青菜补纤维。",
    aliases: ["家常菜", "番茄炒蛋", "西红柿炒鸡蛋", "米饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-home-green-pepper-pork",
    brand: "家常菜 / 自己做饭",
    title: "青椒肉丝 + 米饭",
    scene: "local_meal",
    foodType: "家常小炒",
    category: "meal",
    items: ["青椒肉丝", "米饭 1 碗", "紫菜蛋花汤"],
    macros: { protein: 36, carbs: 82, fat: 24, calories: 690, fiber: 7 },
    note: "瘦肉切丝很快熟，适合工作日午晚餐。",
    caution: "炒肉油多时脂肪会上升，自己做可以少油。",
    aliases: ["家常菜", "青椒肉丝", "小炒肉", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-home-shredded-potato-egg",
    brand: "家常菜 / 自己做饭",
    title: "酸辣土豆丝 + 煎蛋 + 米饭",
    scene: "local_meal",
    foodType: "家常素菜",
    category: "meal",
    items: ["酸辣土豆丝", "煎蛋 2 个", "米饭半碗"],
    macros: { protein: 20, carbs: 72, fat: 22, calories: 565, fiber: 6 },
    note: "便宜好做，土豆和米饭都是碳水，米饭半碗会更稳。",
    aliases: ["家常菜", "土豆丝", "酸辣土豆丝", "鸡蛋"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-home-tofu-pork-rice",
    brand: "家常菜 / 自己做饭",
    title: "家常豆腐 + 瘦肉片 + 米饭",
    scene: "local_meal",
    foodType: "豆腐家常菜",
    category: "meal",
    items: ["家常豆腐", "瘦肉片", "米饭 1 碗", "青菜"],
    macros: { protein: 42, carbs: 78, fat: 28, calories: 735, fiber: 8 },
    note: "豆腐和瘦肉一起做，蛋白质比较稳，也很适合带饭。",
    aliases: ["家常菜", "家常豆腐", "豆腐", "瘦肉"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-home-minced-pork-eggplant",
    brand: "家常菜 / 自己做饭",
    title: "肉末茄子 + 青菜 + 半份饭",
    scene: "local_meal",
    foodType: "家常下饭菜",
    category: "meal",
    items: ["肉末茄子", "清炒青菜", "米饭半碗"],
    macros: { protein: 30, carbs: 56, fat: 30, calories: 615, fiber: 9 },
    note: "茄子很吸油，自己做少油版就能保留味道但更可控。",
    caution: "外卖肉末茄子通常油很多。",
    aliases: ["家常菜", "肉末茄子", "茄子", "青菜"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-home-shrimp-egg-rice",
    brand: "家常菜 / 自己做饭",
    title: "虾仁滑蛋 + 米饭",
    scene: "local_meal",
    foodType: "高蛋白家常菜",
    category: "meal",
    items: ["虾仁滑蛋", "米饭 1 碗", "凉拌黄瓜"],
    macros: { protein: 42, carbs: 76, fat: 20, calories: 660, fiber: 5 },
    note: "虾仁和鸡蛋都很快熟，适合想省事但又要补蛋白的时候。",
    aliases: ["家常菜", "虾仁滑蛋", "虾仁炒蛋", "鸡蛋"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-home-mushroom-chicken",
    brand: "家常菜 / 自己做饭",
    title: "香菇滑鸡 + 青菜 + 米饭",
    scene: "local_meal",
    foodType: "家常鸡肉",
    category: "meal",
    items: ["香菇滑鸡", "清炒青菜", "米饭 1 碗"],
    macros: { protein: 44, carbs: 78, fat: 24, calories: 705, fiber: 8 },
    note: "鸡腿肉或鸡胸都可以做，香菇增加风味和一点纤维。",
    aliases: ["家常菜", "香菇滑鸡", "鸡肉", "青菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-home-steamed-fish-rice",
    brand: "家常菜 / 自己做饭",
    title: "清蒸鲈鱼 + 蒜蓉青菜 + 米饭",
    scene: "local_meal",
    foodType: "清淡家常菜",
    category: "meal",
    items: ["清蒸鲈鱼", "蒜蓉青菜", "米饭半碗"],
    macros: { protein: 48, carbs: 48, fat: 16, calories: 530, fiber: 6 },
    note: "清蒸鱼很适合减脂和健康管理，半碗饭不会太撑。",
    aliases: ["家常菜", "清蒸鱼", "鲈鱼", "蒜蓉青菜"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-home-beef-potato",
    brand: "家常菜 / 自己做饭",
    title: "土豆炖牛肉 + 青菜",
    scene: "local_meal",
    foodType: "家常炖菜",
    category: "meal",
    items: ["土豆炖牛肉", "清炒青菜", "米饭半碗"],
    macros: { protein: 44, carbs: 62, fat: 26, calories: 660, fiber: 8 },
    note: "炖菜适合一次多做两顿，土豆已经有碳水，米饭半碗就够。",
    aliases: ["家常菜", "土豆炖牛肉", "牛肉", "土豆"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-home-wintermelon-ribs",
    brand: "家常菜 / 自己做饭",
    title: "冬瓜排骨汤 + 青菜 + 米饭",
    scene: "local_meal",
    foodType: "家常汤菜",
    category: "meal",
    items: ["冬瓜排骨汤", "清炒青菜", "米饭 1 碗"],
    macros: { protein: 36, carbs: 74, fat: 24, calories: 660, fiber: 7 },
    note: "汤菜更舒服，排骨别太肥，米饭按一碗正常饭算。",
    caution: "排骨肥肉多时脂肪会明显更高。",
    aliases: ["家常菜", "冬瓜排骨汤", "排骨汤", "青菜"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-home-wood-ear-egg",
    brand: "家常菜 / 自己做饭",
    title: "木耳炒鸡蛋 + 鸡胸肉 + 米饭",
    scene: "local_meal",
    foodType: "高蛋白家常菜",
    category: "meal",
    items: ["木耳炒鸡蛋", "煎鸡胸肉", "米饭半碗"],
    macros: { protein: 50, carbs: 48, fat: 20, calories: 575, fiber: 7 },
    note: "想吃简单清爽一点时，这组蛋白高、油脂好控。",
    aliases: ["家常菜", "木耳炒鸡蛋", "鸡胸肉", "鸡蛋"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-home-cabbage-tofu",
    brand: "家常菜 / 自己做饭",
    title: "白菜豆腐炖粉条 + 瘦肉",
    scene: "local_meal",
    foodType: "家常炖菜",
    category: "meal",
    items: ["白菜豆腐", "粉条少量", "瘦肉片"],
    macros: { protein: 34, carbs: 46, fat: 18, calories: 485, fiber: 8 },
    note: "北方家常一锅出，粉条少量就好，想更饱可以另加半碗饭。",
    aliases: ["家常菜", "白菜豆腐", "炖粉条", "瘦肉"],
    goalFit: ["health", "fat_loss", "muscle"]
  },
  {
    id: "cat-home-tomato-beef-brisket",
    brand: "家常菜 / 自己做饭",
    title: "番茄牛腩 + 米饭",
    scene: "local_meal",
    foodType: "家常炖菜",
    category: "meal",
    items: ["番茄牛腩", "米饭 1 碗", "生菜"],
    macros: { protein: 42, carbs: 82, fat: 30, calories: 765, fiber: 7 },
    note: "酸甜开胃，适合训练日正餐；牛腩肥瘦差异会影响脂肪。",
    caution: "牛腩偏肥时热量会明显增加。",
    aliases: ["家常菜", "番茄牛腩", "西红柿牛腩", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-home-garlic-greens-egg",
    brand: "家常菜 / 自己做饭",
    title: "蒜蓉青菜 + 鸡蛋豆腐 + 半份饭",
    scene: "local_meal",
    foodType: "轻家常菜",
    category: "meal",
    items: ["蒜蓉青菜", "鸡蛋豆腐", "米饭半碗"],
    macros: { protein: 24, carbs: 48, fat: 18, calories: 455, fiber: 8 },
    note: "晚上不想吃太重时很合适，清淡但不至于只吃草。",
    aliases: ["家常菜", "蒜蓉青菜", "鸡蛋豆腐", "青菜"],
    goalFit: ["fat_loss", "weight_loss", "health"]
  },
  {
    id: "cat-home-celery-beef",
    brand: "家常菜 / 自己做饭",
    title: "芹菜炒牛肉 + 米饭",
    scene: "local_meal",
    foodType: "家常小炒",
    category: "meal",
    items: ["芹菜炒牛肉", "米饭 1 碗", "番茄蛋汤"],
    macros: { protein: 42, carbs: 78, fat: 24, calories: 700, fiber: 8 },
    note: "牛肉补蛋白，芹菜很适合做家常高纤维配菜。",
    aliases: ["家常菜", "芹菜炒牛肉", "牛肉", "芹菜"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-home-carrot-chicken",
    brand: "家常菜 / 自己做饭",
    title: "胡萝卜鸡丁 + 青菜 + 米饭",
    scene: "local_meal",
    foodType: "家常鸡肉",
    category: "meal",
    items: ["胡萝卜鸡丁", "清炒青菜", "米饭 1 碗"],
    macros: { protein: 42, carbs: 82, fat: 20, calories: 680, fiber: 9 },
    note: "鸡丁切小块很快熟，适合新手自己做饭。",
    aliases: ["家常菜", "胡萝卜鸡丁", "鸡肉", "青菜"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-bbq-lean-skewers",
    brand: "烧烤",
    title: "牛肉串 + 鸡翅 + 烤蔬菜",
    scene: "local_meal",
    foodType: "烧烤",
    category: "meal",
    items: ["牛肉串 6 串", "鸡翅 2 个", "烤韭菜", "烤蘑菇", "无糖饮料"],
    macros: { protein: 52, carbs: 30, fat: 34, calories: 650, fiber: 6 },
    note: "想吃烧烤时多选肉和蔬菜，少点烤馒头、少刷甜酱。",
    caution: "钠和油脂通常偏高，减重用户偶尔吃更好。",
    aliases: ["烧烤", "烤串", "牛肉串", "鸡翅"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-lean",
    brand: "烤肉店",
    title: "瘦牛肉 + 生菜包 + 半份饭",
    scene: "local_meal",
    foodType: "烤肉",
    category: "meal",
    items: ["瘦牛肉 180g", "生菜包", "泡菜", "半份米饭"],
    macros: { protein: 58, carbs: 48, fat: 30, calories: 695, fiber: 7 },
    note: "烤肉也能吃得比较稳，用生菜包和半份饭控制油脂和碳水。",
    caution: "五花肉、肥牛和甜酱会把脂肪拉高。",
    aliases: ["烤肉", "韩式烤肉", "牛肉", "生菜"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-grilled-fish",
    brand: "烤鱼",
    title: "清江鱼 + 蔬菜 + 半份米饭",
    scene: "local_meal",
    foodType: "烤鱼",
    category: "meal",
    items: ["清江鱼", "豆腐", "金针菇", "青笋", "半份米饭"],
    macros: { protein: 62, carbs: 48, fat: 32, calories: 730, fiber: 9 },
    note: "鱼肉蛋白很强，配菜选豆腐和蔬菜会比加宽粉更适合减脂。",
    caution: "重油锅底会让脂肪偏高。",
    aliases: ["烤鱼", "清江鱼", "豆腐", "金针菇"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-sour-fish-rice",
    brand: "酸菜鱼",
    title: "酸菜鱼 + 青菜 + 半份饭",
    scene: "local_meal",
    foodType: "鱼类正餐",
    category: "meal",
    items: ["酸菜鱼", "青菜", "半份米饭"],
    macros: { protein: 48, carbs: 50, fat: 26, calories: 640, fiber: 6 },
    note: "想吃重口味正餐时，用半份饭和青菜兜住整体结构。",
    caution: "汤底钠较高，别把汤喝太多。",
    aliases: ["酸菜鱼", "鱼", "米饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-luosifen-egg-veg",
    brand: "螺蛳粉",
    title: "螺蛳粉 + 鸡蛋 + 青菜",
    scene: "local_meal",
    foodType: "粉面",
    category: "meal",
    items: ["螺蛳粉 1 碗", "鸡蛋 1 个", "青菜加量"],
    macros: { protein: 26, carbs: 92, fat: 26, calories: 710, fiber: 6 },
    note: "碳水很足，适合训练日；加蛋和青菜能稍微补齐结构。",
    caution: "汤底和配料钠偏高，减脂用户注意频率。",
    aliases: ["螺蛳粉", "粉", "鸡蛋", "青菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-maocai-beef-tofu",
    brand: "冒菜",
    title: "牛肉豆腐冒菜 + 半份饭",
    scene: "local_meal",
    foodType: "冒菜",
    category: "meal",
    items: ["牛肉片", "豆腐", "青菜", "菌菇", "半份米饭"],
    macros: { protein: 44, carbs: 56, fat: 28, calories: 650, fiber: 10 },
    note: "冒菜和麻辣烫一样可控，少粉、多肉豆腐和青菜会好很多。",
    caution: "重油红汤会提高脂肪。",
    aliases: ["冒菜", "牛肉", "豆腐", "青菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-malatang-lean-bowl",
    brand: "麻辣烫",
    title: "牛肉豆腐青菜碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["牛肉片", "豆腐皮", "油麦菜", "金针菇", "少粉", "少麻酱"],
    macros: { protein: 42, carbs: 40, fat: 22, calories: 550, fiber: 11 },
    note: "这是更偏减脂的麻辣烫组合，蛋白和纤维比较高。",
    aliases: ["麻辣烫", "牛肉", "豆腐皮", "青菜"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-malatang-training-bowl",
    brand: "麻辣烫",
    title: "训练日宽粉肉丸碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["宽粉半份", "牛肉丸", "鸡肉片", "青菜", "豆腐"],
    macros: { protein: 44, carbs: 78, fat: 26, calories: 720, fiber: 9 },
    note: "训练日缺碳水时可以加宽粉，但别再叠方便面和麻酱。",
    caution: "丸子和宽粉多了热量会上得很快。",
    aliases: ["麻辣烫", "宽粉", "牛肉丸", "鸡肉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hotpot-carb-training",
    brand: "海底捞",
    title: "番茄锅牛肉 + 小份捞面",
    scene: "hotpot",
    foodType: "火锅训练餐",
    category: "meal",
    items: ["番茄锅", "牛肉片 150g", "捞面小份", "豆皮", "青菜"],
    macros: { protein: 48, carbs: 62, fat: 24, calories: 660, fiber: 7 },
    note: "训练日缺碳水又想吃火锅时，小份捞面比乱加油碟更可控。",
    aliases: ["海底捞", "捞面", "番茄锅", "牛肉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hotpot-veg-protein",
    brand: "海底捞",
    title: "清汤锅虾滑毛肚蔬菜",
    scene: "hotpot",
    foodType: "火锅轻正餐",
    category: "meal",
    items: ["清汤锅", "虾滑半份", "毛肚半份", "豆腐", "蔬菜拼盘"],
    macros: { protein: 46, carbs: 24, fat: 20, calories: 475, fiber: 10 },
    note: "低碳日或减脂日想吃火锅，可以用这个组合。",
    aliases: ["海底捞", "清汤锅", "虾滑", "毛肚", "蔬菜"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-light-sweet-potato-yogurt",
    brand: "水果加餐",
    title: "烤红薯 + 无糖酸奶",
    scene: "fruit_snack",
    foodType: "轻加餐",
    category: "topup",
    items: ["小烤红薯 1 个", "无糖酸奶 1 杯"],
    macros: { protein: 12, carbs: 46, fat: 4, calories: 265, fiber: 6 },
    note: "平均达成超过 80% 后，用这种轻加餐补一点碳水和纤维就够了。",
    aliases: ["红薯", "酸奶", "水果加餐", "轻补"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-light-corn-milk",
    brand: "便利店加餐",
    title: "玉米 + 低脂牛奶",
    scene: "convenience",
    foodType: "轻加餐",
    category: "topup",
    items: ["玉米 1 根", "低脂牛奶 250ml"],
    macros: { protein: 13, carbs: 36, fat: 6, calories: 250, fiber: 4 },
    note: "轻补碳水和蛋白，适合今天已经吃得差不多的时候。",
    aliases: ["玉米", "牛奶", "便利店", "加餐"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-light-cucumber-tomato-egg",
    brand: "便利店 / 菜市场",
    title: "小番茄黄瓜 + 茶叶蛋",
    scene: "fruit_snack",
    foodType: "轻补纤维",
    category: "topup",
    items: ["小番茄 1 盒", "黄瓜 1 根", "茶叶蛋 1 个"],
    macros: { protein: 10, carbs: 18, fat: 6, calories: 165, fiber: 5 },
    note: "今天快达标但纤维差一点时，很适合用这个补。",
    aliases: ["小番茄", "黄瓜", "茶叶蛋", "轻补"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-light-protein-bar",
    brand: "便利店 / 健身补剂",
    title: "蛋白棒 + 无糖茶",
    scene: "supplement",
    foodType: "蛋白零食",
    category: "protein",
    items: ["蛋白棒 1 根", "无糖茶"],
    macros: { protein: 20, carbs: 18, fat: 7, calories: 220, fiber: 5 },
    note: "只差一点蛋白又不想吃正餐时，蛋白棒很省事。",
    aliases: ["蛋白棒", "无糖茶", "健身补剂", "零食"],
    goalFit: ["muscle", "fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-light-edamame-fruit",
    brand: "便利店 / 零食加餐",
    title: "毛豆 + 苹果",
    scene: "fruit_snack",
    foodType: "轻补蛋白纤维",
    category: "topup",
    items: ["毛豆 1 小盒", "苹果 1 个"],
    macros: { protein: 13, carbs: 34, fat: 5, calories: 235, fiber: 9 },
    note: "轻补纤维和植物蛋白，适合平均达成已经比较高的时候。",
    aliases: ["毛豆", "苹果", "零食", "水果"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-light-cottage-cheese-fruit",
    brand: "便利店 / 超市",
    title: "低脂奶酪杯 + 蓝莓",
    scene: "fruit_snack",
    foodType: "乳制品加餐",
    category: "topup",
    items: ["低脂奶酪杯", "蓝莓一小盒"],
    macros: { protein: 18, carbs: 22, fat: 5, calories: 205, fiber: 4 },
    note: "想吃甜一点但又想补蛋白时，这个比奶茶更稳。",
    aliases: ["奶酪", "蓝莓", "乳制品", "水果"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-sichuan-kungpao-chicken",
    brand: "川菜馆",
    title: "宫保鸡丁 + 清炒时蔬 + 半份饭",
    scene: "local_meal",
    foodType: "川菜小炒",
    category: "meal",
    items: ["宫保鸡丁", "清炒时蔬", "半份米饭"],
    macros: { protein: 42, carbs: 58, fat: 28, calories: 660, fiber: 8 },
    note: "川菜常见点菜组合，蛋白和碳水都够，少油少糖会更适合日常。",
    caution: "宫保汁和花生会增加脂肪与热量。",
    aliases: ["川菜", "宫保鸡丁", "小炒", "米饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-sichuan-mapo-tofu-beef",
    brand: "川菜馆",
    title: "麻婆豆腐 + 水煮牛肉少油版",
    scene: "local_meal",
    foodType: "川菜正餐",
    category: "meal",
    items: ["麻婆豆腐", "水煮牛肉少油", "青菜", "半份米饭"],
    macros: { protein: 54, carbs: 48, fat: 36, calories: 745, fiber: 8 },
    note: "想吃重口川菜时，用豆腐和牛肉补蛋白，米饭半份更可控。",
    caution: "水煮类红油多，尽量少喝汤。",
    aliases: ["川菜", "麻婆豆腐", "水煮牛肉", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-sichuan-fish-fragrant-pork",
    brand: "川菜馆",
    title: "鱼香肉丝 + 番茄蛋汤 + 米饭",
    scene: "local_meal",
    foodType: "川菜小炒",
    category: "meal",
    items: ["鱼香肉丝", "番茄蛋汤", "米饭 1 碗"],
    macros: { protein: 38, carbs: 86, fat: 30, calories: 765, fiber: 7 },
    note: "很常见的下饭菜，训练日缺碳水时适合。",
    caution: "鱼香汁偏甜偏油，减脂时米饭减半更稳。",
    aliases: ["川菜", "鱼香肉丝", "番茄蛋汤", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hunan-pork-pepper",
    brand: "湘菜馆",
    title: "辣椒炒肉 + 手撕包菜 + 半份饭",
    scene: "local_meal",
    foodType: "湘菜小炒",
    category: "meal",
    items: ["辣椒炒肉", "手撕包菜", "半份米饭"],
    macros: { protein: 42, carbs: 52, fat: 34, calories: 675, fiber: 9 },
    note: "湘菜高频点菜方式，烟火气强，配包菜能补一点纤维。",
    caution: "五花肉和油量会影响很大，减重用户可换瘦肉。",
    aliases: ["湘菜", "辣椒炒肉", "手撕包菜", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hunan-beef-fish-head",
    brand: "湘菜馆",
    title: "小炒黄牛肉 + 剁椒鱼头 + 青菜",
    scene: "local_meal",
    foodType: "湘菜正餐",
    category: "meal",
    items: ["小炒黄牛肉", "剁椒鱼头", "清炒青菜", "半份米饭"],
    macros: { protein: 62, carbs: 50, fat: 34, calories: 760, fiber: 8 },
    note: "湘菜里的高蛋白组合，适合训练日或缺蛋白明显的时候。",
    caution: "剁椒鱼头钠偏高，别把汤汁拌太多饭。",
    aliases: ["湘菜", "小炒黄牛肉", "剁椒鱼头", "青菜"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-hunan-egg-preserved-veg",
    brand: "湘菜馆",
    title: "外婆菜炒蛋 + 香干炒肉 + 米饭",
    scene: "local_meal",
    foodType: "湘菜小炒",
    category: "meal",
    items: ["外婆菜炒蛋", "香干炒肉", "米饭 1 碗"],
    macros: { protein: 44, carbs: 78, fat: 34, calories: 790, fiber: 7 },
    note: "下饭但蛋白也不差，适合午晚餐缺口比较大的时候。",
    caution: "腌菜和香干钠偏高，第二天可以清淡点。",
    aliases: ["湘菜", "外婆菜炒蛋", "香干炒肉", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-cantonese-steamed-fish",
    brand: "粤菜馆",
    title: "清蒸鱼 + 白灼菜心 + 半份饭",
    scene: "local_meal",
    foodType: "粤菜清淡正餐",
    category: "meal",
    items: ["清蒸鱼", "白灼菜心", "半份米饭", "例汤"],
    macros: { protein: 52, carbs: 48, fat: 18, calories: 570, fiber: 7 },
    note: "粤菜里很适合减脂和健康管理的一组，蛋白高、油脂相对低。",
    aliases: ["粤菜", "清蒸鱼", "白灼菜心", "例汤"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"]
  },
  {
    id: "cat-cantonese-white-cut-chicken",
    brand: "粤菜馆",
    title: "白切鸡 + 蒸水蛋 + 青菜",
    scene: "local_meal",
    foodType: "粤菜高蛋白",
    category: "meal",
    items: ["白切鸡去部分皮", "蒸水蛋", "白灼青菜", "半份米饭"],
    macros: { protein: 58, carbs: 45, fat: 26, calories: 650, fiber: 6 },
    note: "蛋白质很稳，适合训练日又不想吃太重油的时候。",
    caution: "鸡皮和蘸料会增加脂肪。",
    aliases: ["粤菜", "白切鸡", "蒸水蛋", "青菜"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-cantonese-dim-sum-light",
    brand: "粤式茶餐厅",
    title: "虾饺烧卖 + 牛肉粥",
    scene: "local_meal",
    foodType: "粤式茶点",
    category: "meal",
    items: ["虾饺 4 个", "烧卖 3 个", "牛肉粥 1 碗", "青菜"],
    macros: { protein: 38, carbs: 82, fat: 18, calories: 650, fiber: 5 },
    note: "早午餐都能用，茶点别全点酥皮类会更稳。",
    caution: "叉烧酥、流沙包这类脂肪和糖更高。",
    aliases: ["粤菜", "虾饺", "烧卖", "牛肉粥", "茶点"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-jiangxi-fried-fish",
    brand: "赣菜 / 江西小炒",
    title: "赣南小炒鱼 + 空心菜 + 半份饭",
    scene: "local_meal",
    foodType: "赣菜小炒",
    category: "meal",
    items: ["赣南小炒鱼", "清炒空心菜", "半份米饭"],
    macros: { protein: 46, carbs: 52, fat: 28, calories: 650, fiber: 8 },
    note: "江西小炒代表组合，鱼肉补蛋白，蔬菜兜住纤维。",
    caution: "小炒鱼偏油偏辣，少汤汁拌饭。",
    aliases: ["赣菜", "江西小炒", "小炒鱼", "空心菜"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-jiangxi-lotus-duck",
    brand: "赣菜 / 江西小炒",
    title: "莲花血鸭 + 藜蒿炒腊肉少量",
    scene: "local_meal",
    foodType: "赣菜正餐",
    category: "meal",
    items: ["莲花血鸭", "藜蒿炒腊肉少量", "青菜", "半份米饭"],
    macros: { protein: 50, carbs: 48, fat: 38, calories: 740, fiber: 8 },
    note: "赣菜风味很足，适合想吃地方菜但仍想补蛋白的时候。",
    caution: "腊肉和鸭肉脂肪、钠都偏高，减重用户少选。",
    aliases: ["赣菜", "江西菜", "莲花血鸭", "藜蒿炒腊肉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-jiangxi-bamboo-pork",
    brand: "赣菜 / 江西小炒",
    title: "井冈烟笋炒肉 + 青菜 + 米饭",
    scene: "local_meal",
    foodType: "赣菜小炒",
    category: "meal",
    items: ["井冈烟笋炒肉", "青菜", "米饭 1 碗"],
    macros: { protein: 42, carbs: 78, fat: 30, calories: 745, fiber: 9 },
    note: "地方小炒里很常见，笋类能补纤维，适合正常正餐。",
    caution: "炒肉油量差异大，外卖可备注少油。",
    aliases: ["赣菜", "烟笋炒肉", "江西小炒", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-jiangzhe-shrimp-tofu",
    brand: "江浙菜馆",
    title: "龙井虾仁 + 家常豆腐 + 半份饭",
    scene: "local_meal",
    foodType: "江浙菜",
    category: "meal",
    items: ["龙井虾仁", "家常豆腐", "半份米饭", "青菜"],
    macros: { protein: 50, carbs: 48, fat: 24, calories: 620, fiber: 7 },
    note: "江浙菜相对温和，虾仁和豆腐能把蛋白补得比较舒服。",
    aliases: ["江浙菜", "龙井虾仁", "家常豆腐", "青菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-jiangzhe-braised-pork",
    brand: "本帮 / 江浙菜",
    title: "红烧肉少量 + 清炒虾仁 + 青菜",
    scene: "local_meal",
    foodType: "本帮菜",
    category: "meal",
    items: ["红烧肉少量", "清炒虾仁", "青菜", "半份米饭"],
    macros: { protein: 46, carbs: 50, fat: 38, calories: 725, fiber: 6 },
    note: "想吃本帮甜口时，把红烧肉当少量快乐项，再用虾仁补蛋白。",
    caution: "红烧肉糖油都高，不适合频繁作为减重餐。",
    aliases: ["江浙菜", "本帮菜", "红烧肉", "虾仁"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-yunnan-mushroom-chicken",
    brand: "云贵菜馆",
    title: "汽锅鸡 + 菌菇拼盘 + 米饭",
    scene: "local_meal",
    foodType: "云贵菜",
    category: "meal",
    items: ["汽锅鸡", "菌菇拼盘", "青菜", "半份米饭"],
    macros: { protein: 52, carbs: 48, fat: 22, calories: 600, fiber: 9 },
    note: "云贵菜近年热度上升，菌菇和鸡肉组合对健康管理很友好。",
    aliases: ["云贵菜", "汽锅鸡", "菌菇", "青菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-guizhou-sour-soup-fish",
    brand: "贵州菜馆",
    title: "酸汤鱼 + 豆腐青菜 + 半份饭",
    scene: "local_meal",
    foodType: "贵州菜",
    category: "meal",
    items: ["酸汤鱼", "豆腐", "青菜", "半份米饭"],
    macros: { protein: 54, carbs: 48, fat: 24, calories: 635, fiber: 8 },
    note: "酸汤鱼蛋白足、口味开胃，适合想吃地方菜又不想太油。",
    caution: "汤底钠不低，少喝汤更好。",
    aliases: ["贵州菜", "酸汤鱼", "豆腐", "青菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-northeast-pot-chicken",
    brand: "东北菜馆",
    title: "小鸡炖蘑菇 + 凉拌菜 + 半份饭",
    scene: "local_meal",
    foodType: "东北菜",
    category: "meal",
    items: ["小鸡炖蘑菇", "凉拌菜", "半份米饭"],
    macros: { protein: 48, carbs: 54, fat: 26, calories: 640, fiber: 8 },
    note: "东北菜分量通常大，点炖菜时把主食减半会更合适。",
    caution: "锅包肉、地三鲜这类油炸或过油菜热量更高。",
    aliases: ["东北菜", "小鸡炖蘑菇", "凉拌菜", "米饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-northwest-lamb-noodle",
    brand: "西北菜馆",
    title: "羊肉串 + 拌面小份 + 凉拌黄瓜",
    scene: "local_meal",
    foodType: "西北菜",
    category: "meal",
    items: ["羊肉串 5 串", "拌面小份", "凉拌黄瓜"],
    macros: { protein: 48, carbs: 70, fat: 30, calories: 740, fiber: 6 },
    note: "西北菜适合训练日补碳水和蛋白，小份面能避免吃太撑。",
    caution: "羊肉串和拌面油脂可能偏高。",
    aliases: ["西北菜", "羊肉串", "拌面", "凉拌黄瓜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-beef-noodle-small",
    brand: "早餐面馆",
    title: "小碗牛肉面 + 茶叶蛋",
    scene: "local_meal",
    foodType: "粉面快餐",
    category: "meal",
    items: ["牛肉面小碗", "茶叶蛋 1 个", "青菜"],
    macros: { protein: 34, carbs: 72, fat: 15, calories: 560, fiber: 5 },
    note: "早餐想吃热乎一点时，小碗面加蛋比大碗纯面更均衡。",
    aliases: ["早餐", "牛肉面", "茶叶蛋", "粉面"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-rice-noodle-egg",
    brand: "早餐粉面店",
    title: "米粉 + 卤蛋 + 青菜",
    scene: "local_meal",
    foodType: "粉面快餐",
    category: "meal",
    items: ["米粉 1 碗", "卤蛋 1 个", "青菜加量"],
    macros: { protein: 24, carbs: 80, fat: 16, calories: 560, fiber: 5 },
    note: "南方常见早餐，青菜和卤蛋能让结构更完整。",
    aliases: ["早餐", "米粉", "卤蛋", "青菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-breakfast-corn-egg-soymilk",
    brand: "早餐店",
    title: "玉米 + 鸡蛋 + 无糖豆浆",
    scene: "local_meal",
    foodType: "中式早餐",
    category: "meal",
    items: ["玉米 1 根", "鸡蛋 2 个", "无糖豆浆"],
    macros: { protein: 24, carbs: 44, fat: 13, calories: 390, fiber: 5 },
    note: "早餐轻一点但蛋白不低，适合不想吃油饼的人。",
    aliases: ["早餐", "玉米", "鸡蛋", "豆浆"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-hotpot-hdl-seafood",
    brand: "海底捞",
    title: "清汤锅海鲜豆腐蔬菜",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["清汤锅", "虾", "鱼片", "豆腐", "蔬菜拼盘"],
    macros: { protein: 54, carbs: 26, fat: 20, calories: 500, fiber: 9 },
    note: "想吃火锅但不想太油时，海鲜、豆腐和蔬菜是比较稳的组合。",
    aliases: ["火锅", "海底捞", "海鲜", "豆腐"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-hotpot-hdl-mushroom",
    brand: "海底捞",
    title: "菌汤锅鸡肉菌菇拼盘",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["菌汤锅", "鸡肉片", "菌菇拼盘", "娃娃菜", "豆皮少量"],
    macros: { protein: 46, carbs: 34, fat: 22, calories: 520, fiber: 11 },
    note: "菌汤锅配鸡肉和菌菇，适合健康管理或休息日。",
    aliases: ["火锅", "菌汤锅", "鸡肉", "菌菇"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-hotpot-chaoshan-beef",
    brand: "潮汕牛肉火锅",
    title: "吊龙嫩肉 + 牛肉丸 + 青菜",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["吊龙 150g", "嫩肉 100g", "牛肉丸 3 个", "青菜", "半份粿条"],
    macros: { protein: 62, carbs: 42, fat: 28, calories: 670, fiber: 6 },
    note: "潮汕牛肉火锅蛋白很足，主食半份就够。",
    caution: "沙茶酱别蘸太多。",
    aliases: ["火锅", "潮汕牛肉", "牛肉丸", "粿条"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hotpot-coconut-chicken",
    brand: "椰子鸡火锅",
    title: "椰子鸡 + 竹荪 + 蔬菜拼盘",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["椰子鸡", "竹荪", "菌菇", "蔬菜拼盘", "半份米饭"],
    macros: { protein: 50, carbs: 48, fat: 22, calories: 590, fiber: 8 },
    note: "比牛油锅轻很多，适合想吃热锅但不想太油。",
    aliases: ["火锅", "椰子鸡", "竹荪", "蔬菜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-hotpot-mini-self-service",
    brand: "自助小火锅",
    title: "肥牛豆腐蔬菜小火锅",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["肥牛 120g", "豆腐", "青菜", "菌菇", "粉丝少量"],
    macros: { protein: 42, carbs: 40, fat: 28, calories: 580, fiber: 8 },
    note: "小火锅分量更好控，粉丝少量就能有满足感。",
    aliases: ["火锅", "自助小火锅", "肥牛", "豆腐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-hotpot-spicy-light",
    brand: "川渝火锅",
    title: "微辣锅鸭血毛肚豆腐",
    scene: "hotpot",
    foodType: "火锅正餐",
    category: "meal",
    items: ["微辣锅", "鸭血", "毛肚", "豆腐", "油麦菜"],
    macros: { protein: 38, carbs: 22, fat: 26, calories: 475, fiber: 8 },
    note: "想吃川渝火锅但当天接近达标时，这个比肉油碟组合轻一些。",
    caution: "红汤和油碟仍会增加脂肪。",
    aliases: ["火锅", "川渝火锅", "鸭血", "毛肚"],
    goalFit: ["fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-malatang-seafood-bowl",
    brand: "麻辣烫",
    title: "虾仁鱼片蔬菜碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["虾仁", "鱼片", "豆腐", "青菜", "菌菇", "少粉"],
    macros: { protein: 44, carbs: 34, fat: 18, calories: 475, fiber: 10 },
    note: "海鲜和豆腐把蛋白补上，少粉少麻酱更适合减脂。",
    aliases: ["麻辣烫", "虾仁", "鱼片", "豆腐"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-malatang-veggie-tofu-bowl",
    brand: "麻辣烫",
    title: "豆腐菌菇蔬菜轻碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "topup",
    items: ["豆腐", "豆皮", "菠菜", "金针菇", "海带", "少麻酱"],
    macros: { protein: 26, carbs: 28, fat: 14, calories: 340, fiber: 12 },
    note: "平均达成较高时，用麻辣烫也可以轻补纤维和蛋白。",
    aliases: ["麻辣烫", "豆腐", "菌菇", "蔬菜"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-malatang-chicken-rice-bowl",
    brand: "杨国福麻辣烫",
    title: "鸡肉青菜半份米饭碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["鸡肉片", "青菜", "豆腐", "菌菇", "半份米饭"],
    macros: { protein: 40, carbs: 56, fat: 18, calories: 550, fiber: 9 },
    note: "把宽粉换半份米饭，整体更像一顿正餐快餐。",
    aliases: ["麻辣烫", "杨国福", "鸡肉", "米饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-malatang-beef-lowcarb",
    brand: "张亮麻辣烫",
    title: "牛肉豆腐低碳碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["牛肉片", "豆腐", "海带", "青菜", "菌菇", "不加粉面"],
    macros: { protein: 42, carbs: 20, fat: 20, calories: 430, fiber: 10 },
    note: "低碳日想吃麻辣烫时可以这样点。",
    aliases: ["麻辣烫", "张亮", "牛肉", "低碳"],
    goalFit: ["fat_loss", "weight_loss", "health"]
  },
  {
    id: "cat-malatang-fish-ball-bowl",
    brand: "麻辣烫",
    title: "鱼丸豆皮蔬菜碗",
    scene: "local_meal",
    foodType: "麻辣烫",
    category: "meal",
    items: ["鱼丸 4 个", "豆皮", "青菜", "菌菇", "土豆片少量"],
    macros: { protein: 32, carbs: 50, fat: 20, calories: 520, fiber: 9 },
    note: "想吃丸子时别再叠午餐肉和方便面，豆皮青菜补结构。",
    aliases: ["麻辣烫", "鱼丸", "豆皮", "土豆片"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-maocai-lean-chicken",
    brand: "冒菜",
    title: "鸡肉豆腐冒菜少油版",
    scene: "local_meal",
    foodType: "冒菜",
    category: "meal",
    items: ["鸡肉片", "豆腐", "豆芽", "青菜", "半份米饭"],
    macros: { protein: 42, carbs: 52, fat: 24, calories: 590, fiber: 9 },
    note: "冒菜当正餐时，少油、多豆腐和青菜会稳很多。",
    aliases: ["冒菜", "鸡肉", "豆腐", "米饭"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-maocai-spicy-beef",
    brand: "冒菜",
    title: "牛肉菌菇冒菜训练碗",
    scene: "local_meal",
    foodType: "冒菜",
    category: "meal",
    items: ["牛肉片", "菌菇", "豆腐皮", "宽粉少量", "青菜"],
    macros: { protein: 46, carbs: 58, fat: 28, calories: 660, fiber: 10 },
    note: "训练日想吃重口时，宽粉少量、牛肉加量就好。",
    caution: "红油汤底别喝太多。",
    aliases: ["冒菜", "牛肉", "宽粉", "菌菇"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-chicken",
    brand: "韩式烤肉",
    title: "鸡腿肉 + 生菜包 + 泡菜",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["鸡腿肉 180g", "生菜包", "泡菜", "半份米饭"],
    macros: { protein: 50, carbs: 48, fat: 28, calories: 650, fiber: 6 },
    note: "鸡腿肉比五花肉更好控脂肪，生菜包很适合补纤维。",
    aliases: ["韩式烤肉", "烤肉店", "鸡腿肉", "生菜包"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-pork-neck",
    brand: "韩式烤肉",
    title: "梅花肉 + 蘑菇 + 生菜包",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["梅花肉 160g", "蘑菇", "生菜包", "泡菜"],
    macros: { protein: 44, carbs: 24, fat: 36, calories: 610, fiber: 6 },
    note: "想吃猪肉烤肉时，蘑菇和生菜包能让一餐更平衡。",
    caution: "梅花肉脂肪不低，减重用户少蘸酱。",
    aliases: ["韩式烤肉", "烤肉店", "梅花肉", "生菜包"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-shrimp-beef",
    brand: "韩式烤肉",
    title: "虾仁 + 瘦牛肉 + 南瓜片",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["虾仁", "瘦牛肉 120g", "南瓜片", "生菜包"],
    macros: { protein: 55, carbs: 34, fat: 22, calories: 560, fiber: 6 },
    note: "海鲜和瘦牛肉组合脂肪更好控，适合减脂期想吃烤肉。",
    aliases: ["韩式烤肉", "虾仁", "瘦牛肉", "南瓜"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-korean-bbq-galbi",
    brand: "韩式烤肉",
    title: "牛小排少量 + 生菜包 + 石锅饭半份",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["牛小排 120g", "生菜包", "泡菜", "石锅饭半份"],
    macros: { protein: 42, carbs: 58, fat: 42, calories: 780, fiber: 6 },
    note: "牛小排适合偶尔快乐，主食半份就够。",
    caution: "牛小排脂肪较高。",
    aliases: ["韩式烤肉", "牛小排", "生菜包", "石锅饭"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-lean-set",
    brand: "韩式烤肉",
    title: "瘦牛肉双拼 + 烤蔬菜",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["瘦牛肉 200g", "烤蘑菇", "烤洋葱", "生菜包"],
    macros: { protein: 62, carbs: 26, fat: 28, calories: 620, fiber: 7 },
    note: "更偏高蛋白低碳，适合低碳日或晚餐。",
    aliases: ["韩式烤肉", "瘦牛肉", "烤蔬菜", "生菜包"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-korean-bbq-bibimbap",
    brand: "韩式烤肉",
    title: "烤牛肉 + 拌饭小份",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["烤牛肉 150g", "拌饭小份", "泡菜", "生菜"],
    macros: { protein: 48, carbs: 70, fat: 26, calories: 700, fiber: 7 },
    note: "训练日缺碳水时可以加小份拌饭。",
    aliases: ["韩式烤肉", "烤牛肉", "拌饭", "泡菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-samgyeopsal-light",
    brand: "韩式烤肉",
    title: "五花肉少量 + 鸡胸肉 + 生菜包",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["五花肉少量", "鸡胸肉 150g", "生菜包", "泡菜"],
    macros: { protein: 52, carbs: 18, fat: 38, calories: 630, fiber: 5 },
    note: "想吃五花肉时少量尝味，用鸡胸肉把蛋白补回来。",
    caution: "五花肉脂肪高，不适合每天吃。",
    aliases: ["韩式烤肉", "五花肉", "鸡胸肉", "生菜包"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-korean-bbq-tofu-beef",
    brand: "韩式烤肉",
    title: "烤牛肉 + 豆腐汤 + 生菜包",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["烤牛肉", "豆腐汤", "生菜包", "半份米饭"],
    macros: { protein: 54, carbs: 50, fat: 28, calories: 670, fiber: 6 },
    note: "豆腐汤让一餐更完整，适合午晚餐。",
    aliases: ["韩式烤肉", "烤牛肉", "豆腐汤", "生菜包"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-skewer-bbq-beef-veg",
    brand: "烧烤摊",
    title: "牛肉串 + 烤蔬菜 + 无糖茶",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "meal",
    items: ["牛肉串 8 串", "烤蘑菇", "烤韭菜", "无糖茶"],
    macros: { protein: 48, carbs: 22, fat: 28, calories: 560, fiber: 6 },
    note: "烧烤里相对稳的组合，少刷酱、少点烤馒头。",
    aliases: ["烧烤", "烤串", "牛肉串", "烤韭菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-skewer-bbq-lamb-cucumber",
    brand: "烧烤摊",
    title: "羊肉串 + 凉拌黄瓜",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "meal",
    items: ["羊肉串 8 串", "凉拌黄瓜", "烤蘑菇"],
    macros: { protein: 42, carbs: 18, fat: 36, calories: 610, fiber: 5 },
    note: "想吃羊肉串时，加黄瓜和蘑菇，别只吃肉串。",
    caution: "羊肉串脂肪和钠偏高。",
    aliases: ["烧烤", "烤串", "羊肉串", "凉拌黄瓜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-skewer-bbq-chicken-wing",
    brand: "烧烤摊",
    title: "鸡翅 + 鸡胗 + 烤蔬菜",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "meal",
    items: ["鸡翅 2 个", "鸡胗 4 串", "烤茄子少油", "烤青椒"],
    macros: { protein: 44, carbs: 26, fat: 32, calories: 610, fiber: 6 },
    note: "鸡胗蛋白不错，烤茄子备注少油会更好。",
    aliases: ["烧烤", "鸡翅", "鸡胗", "烤蔬菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-skewer-bbq-seafood",
    brand: "烧烤摊",
    title: "烤虾 + 烤鱼豆腐 + 烤蔬菜",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "meal",
    items: ["烤虾", "鱼豆腐 4 串", "烤蘑菇", "烤韭菜"],
    macros: { protein: 42, carbs: 24, fat: 22, calories: 465, fiber: 6 },
    note: "烧烤想轻一点，可以多选海鲜和蔬菜。",
    aliases: ["烧烤", "烤虾", "鱼豆腐", "烤韭菜"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-skewer-bbq-tofu-veg",
    brand: "烧烤摊",
    title: "烤豆腐 + 烤韭菜 + 烤蘑菇",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "topup",
    items: ["烤豆腐", "烤韭菜", "烤蘑菇", "无糖茶"],
    macros: { protein: 20, carbs: 24, fat: 14, calories: 300, fiber: 7 },
    note: "夜里想吃烧烤但今天快达标时，用豆腐和蔬菜轻补。",
    aliases: ["烧烤", "烤豆腐", "烤韭菜", "烤蘑菇"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-skewer-bbq-chicken-breast",
    brand: "烧烤摊",
    title: "烤鸡胸肉串 + 烤玉米",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "meal",
    items: ["鸡胸肉串 6 串", "烤玉米半根", "烤青椒"],
    macros: { protein: 48, carbs: 38, fat: 14, calories: 470, fiber: 5 },
    note: "烧烤里更偏训练餐的选法，蛋白高、脂肪相对低。",
    aliases: ["烧烤", "鸡胸肉串", "烤玉米", "烤串"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-skewer-bbq-night-light",
    brand: "烧烤摊",
    title: "鸡肉串 + 烤蔬菜夜宵",
    scene: "local_meal",
    foodType: "烧烤烤串",
    category: "topup",
    items: ["鸡肉串 4 串", "烤蘑菇", "烤娃娃菜", "无糖饮料"],
    macros: { protein: 30, carbs: 18, fat: 16, calories: 335, fiber: 5 },
    note: "夜宵想吃烤串时，控制在小份，别叠主食。",
    aliases: ["烧烤", "烤串", "鸡肉串", "夜宵"],
    goalFit: ["fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-japanese-sashimi-rice",
    brand: "日料店",
    title: "刺身拼盘 + 米饭小份",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["三文鱼刺身", "金枪鱼刺身", "米饭小份", "味增汤"],
    macros: { protein: 46, carbs: 42, fat: 18, calories: 520, fiber: 2 },
    note: "日料里高蛋白的一组，主食小份就够。",
    aliases: ["日料", "刺身", "三文鱼", "味增汤"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-japanese-eel-rice-small",
    brand: "日料店",
    title: "鳗鱼饭小份 + 海藻沙拉",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["鳗鱼饭小份", "海藻沙拉", "味增汤"],
    macros: { protein: 32, carbs: 72, fat: 22, calories: 620, fiber: 4 },
    note: "想吃鳗鱼饭时选小份，用海藻沙拉补一点纤维。",
    caution: "鳗鱼酱汁偏甜。",
    aliases: ["日料", "鳗鱼饭", "海藻沙拉", "味增汤"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-japanese-teriyaki-chicken",
    brand: "日料店",
    title: "照烧鸡腿饭少酱版",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["照烧鸡腿", "米饭半份", "卷心菜丝", "味增汤"],
    macros: { protein: 42, carbs: 58, fat: 24, calories: 620, fiber: 5 },
    note: "照烧少酱能减少糖和热量，更适合作为午晚餐。",
    aliases: ["日料", "照烧鸡腿", "米饭", "味增汤"],
    goalFit: ["muscle", "health", "fat_loss"]
  },
  {
    id: "cat-japanese-soba-egg",
    brand: "日料店",
    title: "冷荞麦面 + 温泉蛋",
    scene: "light_meal",
    foodType: "日料",
    category: "topup",
    items: ["冷荞麦面", "温泉蛋", "海藻小菜"],
    macros: { protein: 22, carbs: 54, fat: 9, calories: 390, fiber: 5 },
    note: "轻一点的日料主食，适合快达标时补碳水。",
    aliases: ["日料", "荞麦面", "温泉蛋", "海藻"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-japanese-salmon-don",
    brand: "日料店",
    title: "三文鱼亲子丼小份",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["三文鱼", "鱼籽少量", "米饭小份", "味增汤"],
    macros: { protein: 36, carbs: 58, fat: 20, calories: 560, fiber: 2 },
    note: "三文鱼脂肪质量较好，小份米饭更稳。",
    aliases: ["日料", "三文鱼", "亲子丼", "味增汤"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-japanese-tempura-control",
    brand: "日料店",
    title: "天妇罗少量 + 刺身 + 沙拉",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["天妇罗 2 件", "刺身", "蔬菜沙拉", "味增汤"],
    macros: { protein: 38, carbs: 34, fat: 24, calories: 505, fiber: 4 },
    note: "想吃天妇罗时少量尝味，用刺身补蛋白。",
    caution: "天妇罗油脂较高。",
    aliases: ["日料", "天妇罗", "刺身", "沙拉"],
    goalFit: ["health", "fat_loss"]
  },
  {
    id: "cat-japanese-beef-don",
    brand: "日式快餐",
    title: "牛肉饭小份 + 温泉蛋",
    scene: "light_meal",
    foodType: "日料快餐",
    category: "meal",
    items: ["牛肉饭小份", "温泉蛋", "味增汤"],
    macros: { protein: 34, carbs: 68, fat: 22, calories: 610, fiber: 3 },
    note: "日式快餐里很常见，适合午饭或晚饭。",
    aliases: ["日料", "日式快餐", "牛肉饭", "温泉蛋"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-japanese-grilled-mackerel",
    brand: "日料店",
    title: "盐烤青花鱼 + 米饭半份",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["盐烤青花鱼", "米饭半份", "味增汤", "海藻小菜"],
    macros: { protein: 42, carbs: 48, fat: 26, calories: 600, fiber: 4 },
    note: "鱼类蛋白和脂肪质量不错，适合健康管理。",
    aliases: ["日料", "青花鱼", "米饭", "味增汤"],
    goalFit: ["health", "muscle"]
  },
  {
    id: "cat-steak-sirloin-potato",
    brand: "西餐厅",
    title: "西冷牛排 + 烤土豆 + 沙拉",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["西冷牛排 180g", "烤土豆", "蔬菜沙拉"],
    macros: { protein: 55, carbs: 45, fat: 32, calories: 690, fiber: 6 },
    note: "西冷蛋白足，训练日配土豆能补碳水。",
    aliases: ["牛排", "西冷", "steak", "沙拉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-ribeye-veg",
    brand: "西餐厅",
    title: "肉眼牛排 + 烤蔬菜",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["肉眼牛排 180g", "烤芦笋", "烤蘑菇"],
    macros: { protein: 50, carbs: 18, fat: 44, calories: 680, fiber: 5 },
    note: "肉眼更香但脂肪也高，适合低碳日或偶尔快乐。",
    caution: "减重用户优先选西冷或菲力。",
    aliases: ["牛排", "肉眼", "ribeye", "烤蔬菜"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-filet-salad",
    brand: "西餐厅",
    title: "菲力牛排 + 蔬菜沙拉",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["菲力牛排 160g", "蔬菜沙拉", "黑胡椒汁少量"],
    macros: { protein: 48, carbs: 18, fat: 20, calories: 445, fiber: 5 },
    note: "菲力脂肪更低，适合减脂期想吃牛排。",
    aliases: ["牛排", "菲力", "filet", "沙拉"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-steak-tenderloin-rice",
    brand: "西餐厅",
    title: "牛柳粒 + 糙米饭 + 沙拉",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["牛柳粒", "糙米饭半份", "蔬菜沙拉"],
    macros: { protein: 46, carbs: 52, fat: 24, calories: 610, fiber: 7 },
    note: "更像健身餐的牛排吃法，适合午饭晚饭。",
    aliases: ["牛排", "牛柳", "糙米饭", "沙拉"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-steak-salad-light",
    brand: "西式轻食",
    title: "牛排沙拉 + 全麦面包",
    scene: "light_meal",
    foodType: "牛排轻食",
    category: "topup",
    items: ["牛排片", "蔬菜沙拉", "全麦面包 1 片"],
    macros: { protein: 36, carbs: 28, fat: 18, calories: 420, fiber: 7 },
    note: "快达标时想吃牛排，可以选这种轻食版。",
    aliases: ["牛排", "沙拉", "全麦面包", "轻食"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-steak-bowl-pasta",
    brand: "西餐厅",
    title: "牛排意面小份",
    scene: "light_meal",
    foodType: "牛排意面",
    category: "meal",
    items: ["牛排片", "意面小份", "番茄酱汁", "沙拉"],
    macros: { protein: 42, carbs: 72, fat: 28, calories: 730, fiber: 6 },
    note: "训练日缺碳水时可用，意面小份更好控。",
    aliases: ["牛排", "意面", "西餐", "沙拉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-pepper-lunch",
    brand: "铁板牛排饭",
    title: "铁板牛排饭半份饭",
    scene: "fast_food",
    foodType: "牛排快餐",
    category: "meal",
    items: ["铁板牛排", "米饭半份", "玉米粒", "青菜"],
    macros: { protein: 44, carbs: 58, fat: 30, calories: 680, fiber: 5 },
    note: "商场常见牛排快餐，半份饭能降低热量。",
    caution: "黄油和黑椒汁别加太多。",
    aliases: ["牛排", "铁板牛排", "牛排饭", "快餐"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-surf-turf",
    brand: "西餐厅",
    title: "牛排 + 虾仁 + 烤蔬菜",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["牛排 150g", "虾仁", "烤蔬菜"],
    macros: { protein: 62, carbs: 20, fat: 30, calories: 600, fiber: 5 },
    note: "高蛋白低碳，适合晚餐或低碳日。",
    aliases: ["牛排", "虾仁", "烤蔬菜", "西餐"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-steak-hamburg-steak",
    brand: "西式简餐",
    title: "汉堡牛排 + 土豆泥 + 沙拉",
    scene: "fast_food",
    foodType: "牛排简餐",
    category: "meal",
    items: ["汉堡牛排", "土豆泥", "蔬菜沙拉"],
    macros: { protein: 38, carbs: 48, fat: 32, calories: 650, fiber: 6 },
    note: "比纯汉堡更像正餐，但酱汁要少一点。",
    caution: "汉堡牛排可能脂肪偏高。",
    aliases: ["牛排", "汉堡牛排", "土豆泥", "沙拉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-lowfat-box",
    brand: "健身餐",
    title: "瘦牛排健身盒饭",
    scene: "light_meal",
    foodType: "牛排健身餐",
    category: "meal",
    items: ["瘦牛排", "糙米饭半份", "西兰花", "鸡蛋"],
    macros: { protein: 58, carbs: 46, fat: 18, calories: 575, fiber: 8 },
    note: "牛排也可以做成健身餐，适合训练后。",
    aliases: ["牛排", "健身餐", "糙米饭", "西兰花"],
    goalFit: ["muscle", "fat_loss", "health"]
  },
  {
    id: "cat-western-chicken-wrap",
    brand: "西式快餐",
    title: "烤鸡肉卷 + 沙拉",
    scene: "fast_food",
    foodType: "西式快餐",
    category: "topup",
    items: ["烤鸡肉卷", "蔬菜沙拉", "无糖饮料"],
    macros: { protein: 34, carbs: 42, fat: 16, calories: 450, fiber: 6 },
    note: "比炸鸡卷轻一点，适合补蛋白和碳水。",
    aliases: ["西式快餐", "鸡肉卷", "沙拉"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-western-turkey-sandwich",
    brand: "西式轻食",
    title: "火鸡胸三明治",
    scene: "fast_food",
    foodType: "西式快餐",
    category: "topup",
    items: ["火鸡胸三明治", "生菜番茄", "无糖咖啡"],
    macros: { protein: 32, carbs: 46, fat: 10, calories: 405, fiber: 6 },
    note: "轻一点的西式快餐，适合午后加餐或晚餐轻吃。",
    aliases: ["三明治", "西式快餐", "火鸡胸"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-western-pizza-protein",
    brand: "西式快餐",
    title: "薄底披萨 + 烤鸡沙拉",
    scene: "fast_food",
    foodType: "西式快餐",
    category: "meal",
    items: ["薄底披萨 2 片", "烤鸡沙拉"],
    macros: { protein: 42, carbs: 62, fat: 26, calories: 650, fiber: 7 },
    note: "想吃披萨时用烤鸡沙拉补蛋白，别整张披萨当一餐。",
    aliases: ["披萨", "西式快餐", "烤鸡沙拉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-coffee-americano-egg",
    brand: "瑞幸 / 便利店",
    title: "美式咖啡 + 茶叶蛋 + 香蕉",
    scene: "tea_coffee",
    foodType: "咖啡加餐",
    category: "topup",
    items: ["美式咖啡", "茶叶蛋", "香蕉"],
    macros: { protein: 10, carbs: 30, fat: 6, calories: 215, fiber: 3 },
    note: "咖啡配一点蛋白和碳水，比只喝咖啡更稳。",
    aliases: ["咖啡", "美式", "茶叶蛋", "香蕉"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-tea-oat-milk-light",
    brand: "茶饮店",
    title: "燕麦奶茶少糖小杯",
    scene: "tea_coffee",
    foodType: "茶饮配置",
    category: "topup",
    items: ["燕麦奶茶小杯", "少糖", "不加奶盖"],
    macros: { protein: 6, carbs: 34, fat: 8, calories: 235, fiber: 1 },
    note: "想喝奶茶时，小杯少糖、不加奶盖是更稳的配置。",
    aliases: ["奶茶", "燕麦奶", "少糖", "茶饮"],
    goalFit: ["health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-coffee-protein-latte",
    brand: "咖啡店 / 便利店",
    title: "拿铁 + 蛋白棒",
    scene: "tea_coffee",
    foodType: "咖啡加餐",
    category: "protein",
    items: ["无糖拿铁", "蛋白棒 1 根"],
    macros: { protein: 28, carbs: 28, fat: 12, calories: 330, fiber: 5 },
    note: "咖啡和补剂组合，适合蛋白差一点的下午。",
    aliases: ["咖啡", "拿铁", "蛋白棒", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-tea-pure-fruit-light",
    brand: "喜茶 / 古茗",
    title: "纯茶 + 水果杯",
    scene: "tea_coffee",
    foodType: "茶饮加餐",
    category: "topup",
    items: ["无糖纯茶", "水果杯"],
    macros: { protein: 2, carbs: 32, fat: 1, calories: 145, fiber: 5 },
    note: "只想喝点东西又差纤维时，用纯茶配水果杯就够。",
    aliases: ["茶饮", "纯茶", "水果杯", "喜茶"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-convenience-tuna-sandwich",
    brand: "便利店",
    title: "金枪鱼三明治 + 无糖酸奶",
    scene: "convenience",
    foodType: "便利店组合",
    category: "topup",
    items: ["金枪鱼三明治", "无糖酸奶"],
    macros: { protein: 28, carbs: 42, fat: 12, calories: 390, fiber: 4 },
    note: "便利店里容易买到，适合轻晚餐或加餐。",
    aliases: ["便利店", "三明治", "酸奶", "金枪鱼"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-convenience-bento-light",
    brand: "便利店",
    title: "鸡肉便当半份饭",
    scene: "convenience",
    foodType: "便利店快餐",
    category: "meal",
    items: ["鸡肉便当", "米饭半份", "蔬菜加量"],
    macros: { protein: 36, carbs: 58, fat: 18, calories: 560, fiber: 6 },
    note: "便当也可以控量，饭少一点，菜多一点。",
    aliases: ["便利店", "便当", "鸡肉", "快餐"],
    goalFit: ["health", "fat_loss", "muscle"]
  },
  {
    id: "cat-convenience-salad-egg",
    brand: "便利店",
    title: "鸡胸沙拉 + 茶叶蛋",
    scene: "convenience",
    foodType: "便利店轻食",
    category: "topup",
    items: ["鸡胸沙拉", "茶叶蛋"],
    macros: { protein: 34, carbs: 18, fat: 12, calories: 315, fiber: 7 },
    note: "快达标时很适合，轻补蛋白和纤维。",
    aliases: ["便利店", "鸡胸沙拉", "茶叶蛋", "轻食"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-convenience-yogurt-oats",
    brand: "便利店",
    title: "酸奶燕麦杯 + 香蕉",
    scene: "convenience",
    foodType: "便利店加餐",
    category: "topup",
    items: ["无糖酸奶", "燕麦杯", "香蕉"],
    macros: { protein: 15, carbs: 52, fat: 7, calories: 330, fiber: 7 },
    note: "轻补碳水和纤维，适合训练前后。",
    aliases: ["便利店", "酸奶", "燕麦", "香蕉"],
    goalFit: ["health", "muscle", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-convenience-shrimp-roll",
    brand: "便利店",
    title: "虾仁饭团 + 鸡胸肉肠",
    scene: "convenience",
    foodType: "便利店组合",
    category: "topup",
    items: ["虾仁饭团", "鸡胸肉肠", "无糖茶"],
    macros: { protein: 25, carbs: 42, fat: 7, calories: 335, fiber: 2 },
    note: "便利店训练前小餐，简单好执行。",
    aliases: ["便利店", "饭团", "鸡胸肉肠", "无糖茶"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-light-meal-quinoa-chicken",
    brand: "轻食店",
    title: "藜麦鸡胸沙拉",
    scene: "light_meal",
    foodType: "轻食",
    category: "topup",
    items: ["鸡胸肉", "藜麦", "生菜", "番茄", "油醋汁"],
    macros: { protein: 38, carbs: 36, fat: 14, calories: 425, fiber: 9 },
    note: "轻食里比较完整的一份，适合减脂和健康管理。",
    aliases: ["轻食", "鸡胸沙拉", "藜麦", "沙拉"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-light-meal-tuna-potato",
    brand: "轻食店",
    title: "金枪鱼土豆沙拉",
    scene: "light_meal",
    foodType: "轻食",
    category: "topup",
    items: ["金枪鱼", "土豆", "生菜", "玉米", "油醋汁"],
    macros: { protein: 32, carbs: 42, fat: 12, calories: 405, fiber: 7 },
    note: "补一点碳水和蛋白，适合午后或晚餐轻吃。",
    aliases: ["轻食", "金枪鱼", "土豆沙拉", "沙拉"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-light-meal-egg-avocado",
    brand: "轻食店",
    title: "鸡蛋牛油果开放三明治",
    scene: "light_meal",
    foodType: "轻食",
    category: "topup",
    items: ["全麦面包", "鸡蛋", "牛油果少量", "生菜"],
    macros: { protein: 20, carbs: 34, fat: 18, calories: 380, fiber: 8 },
    note: "轻补脂肪和纤维，适合不太饿的时候。",
    aliases: ["轻食", "开放三明治", "牛油果", "鸡蛋"],
    goalFit: ["health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-fruit-kiwi-yogurt",
    brand: "水果加餐",
    title: "猕猴桃 + 无糖酸奶",
    scene: "fruit_snack",
    foodType: "水果加餐",
    category: "topup",
    items: ["猕猴桃 2 个", "无糖酸奶 1 杯"],
    macros: { protein: 10, carbs: 32, fat: 4, calories: 205, fiber: 7 },
    note: "纤维和维生素都不错，适合快达标后的轻补。",
    aliases: ["水果", "猕猴桃", "酸奶", "加餐"],
    goalFit: ["fat_loss", "weight_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-fruit-grape-cheese",
    brand: "水果加餐",
    title: "葡萄 + 低脂奶酪杯",
    scene: "fruit_snack",
    foodType: "水果加餐",
    category: "topup",
    items: ["葡萄一小盒", "低脂奶酪杯"],
    macros: { protein: 16, carbs: 34, fat: 5, calories: 245, fiber: 3 },
    note: "想吃甜一点时，用奶酪补蛋白。",
    aliases: ["水果", "葡萄", "奶酪", "加餐"],
    goalFit: ["health", "fat_loss"],
    lightOnly: true
  },
  {
    id: "cat-fruit-pear-jerky",
    brand: "零食加餐",
    title: "梨 + 低糖牛肉干",
    scene: "fruit_snack",
    foodType: "水果零食",
    category: "topup",
    items: ["梨 1 个", "低糖牛肉干 30g"],
    macros: { protein: 16, carbs: 30, fat: 3, calories: 215, fiber: 5 },
    note: "蛋白和纤维差一点时，水果零食就能补上。",
    aliases: ["水果", "梨", "牛肉干", "零食"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-supplement-whey-banana",
    brand: "健身补剂",
    title: "蛋白粉 + 香蕉",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["乳清蛋白 1 勺", "香蕉 1 根"],
    macros: { protein: 28, carbs: 31, fat: 2, calories: 255, fiber: 3 },
    note: "训练后蛋白和碳水都差一点时很省事。",
    aliases: ["蛋白粉", "乳清", "香蕉", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-supplement-whey-oats",
    brand: "健身补剂",
    title: "蛋白粉燕麦杯",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["乳清蛋白 1 勺", "燕麦 30g", "低脂牛奶"],
    macros: { protein: 36, carbs: 34, fat: 7, calories: 345, fiber: 5 },
    note: "更像一份轻正餐，适合训练后或夜间补充。",
    aliases: ["蛋白粉", "燕麦", "乳清", "健身补剂"],
    goalFit: ["muscle", "health"],
    lightOnly: true
  },
  {
    id: "cat-supplement-casein-yogurt",
    brand: "健身补剂",
    title: "酪蛋白 + 无糖酸奶",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["酪蛋白半勺", "无糖酸奶"],
    macros: { protein: 26, carbs: 12, fat: 4, calories: 190, fiber: 0 },
    note: "夜里只差蛋白时，很轻的一种补法。",
    aliases: ["酪蛋白", "酸奶", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-supplement-protein-bar-milk",
    brand: "健身补剂",
    title: "蛋白棒 + 低脂牛奶",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["蛋白棒 1 根", "低脂牛奶"],
    macros: { protein: 30, carbs: 28, fat: 9, calories: 310, fiber: 5 },
    note: "忙的时候直接补，不用点正餐。",
    aliases: ["蛋白棒", "牛奶", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-supplement-soy-protein",
    brand: "健身补剂",
    title: "植物蛋白粉 + 无糖豆浆",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["植物蛋白粉 1 勺", "无糖豆浆"],
    macros: { protein: 32, carbs: 12, fat: 6, calories: 230, fiber: 2 },
    note: "乳糖不耐受时可以用植物蛋白。",
    aliases: ["蛋白粉", "植物蛋白", "豆浆", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-supplement-whey-coffee",
    brand: "健身补剂",
    title: "蛋白咖啡",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["乳清蛋白半勺", "美式咖啡", "低脂牛奶"],
    macros: { protein: 20, carbs: 10, fat: 4, calories: 155, fiber: 0 },
    note: "想喝咖啡又差一点蛋白时，用这个很轻。",
    aliases: ["蛋白粉", "咖啡", "乳清", "健身补剂"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-supplement-creatine-meal-note",
    brand: "健身补剂",
    title: "蛋白粉 + 肌酸水",
    scene: "supplement",
    foodType: "健身补剂",
    category: "protein",
    items: ["乳清蛋白 1 勺", "肌酸水", "香蕉半根"],
    macros: { protein: 27, carbs: 16, fat: 2, calories: 190, fiber: 1 },
    note: "肌酸本身几乎不提供热量，主要由蛋白粉和香蕉补营养。",
    aliases: ["蛋白粉", "肌酸", "乳清", "健身补剂"],
    goalFit: ["muscle", "fat_loss", "health"],
    lightOnly: true
  },
  {
    id: "cat-korean-bbq-duck-breast",
    brand: "韩式烤肉",
    title: "鸭胸肉 + 生菜包 + 泡菜",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["鸭胸肉 160g", "生菜包", "泡菜", "烤蘑菇"],
    macros: { protein: 46, carbs: 22, fat: 24, calories: 500, fiber: 6 },
    note: "想吃烤肉但不想太油时，鸭胸肉比五花肉更好控。",
    aliases: ["韩式烤肉", "烤肉店", "鸭胸肉", "生菜包"],
    goalFit: ["fat_loss", "health", "muscle"]
  },
  {
    id: "cat-korean-bbq-scallop-beef",
    brand: "韩式烤肉",
    title: "扇贝 + 瘦牛肉 + 烤蔬菜",
    scene: "local_meal",
    foodType: "韩式烤肉",
    category: "meal",
    items: ["扇贝", "瘦牛肉 120g", "烤蔬菜", "生菜包"],
    macros: { protein: 56, carbs: 20, fat: 20, calories: 485, fiber: 5 },
    note: "海鲜加瘦牛肉，蛋白高且脂肪更稳。",
    aliases: ["韩式烤肉", "扇贝", "瘦牛肉", "烤蔬菜"],
    goalFit: ["fat_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-japanese-chicken-oyakodon",
    brand: "日料店",
    title: "亲子丼小份 + 味增汤",
    scene: "light_meal",
    foodType: "日料",
    category: "meal",
    items: ["亲子丼小份", "味增汤", "海藻小菜"],
    macros: { protein: 34, carbs: 62, fat: 18, calories: 550, fiber: 3 },
    note: "日料里很常见的鸡蛋鸡肉饭，小份更适合日常。",
    aliases: ["日料", "亲子丼", "味增汤", "鸡肉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-japanese-tofu-salmon",
    brand: "日料店",
    title: "三文鱼豆腐沙拉",
    scene: "light_meal",
    foodType: "日料轻食",
    category: "topup",
    items: ["三文鱼", "豆腐", "生菜", "味增汤"],
    macros: { protein: 34, carbs: 14, fat: 18, calories: 355, fiber: 4 },
    note: "快达标时用日料轻补蛋白，主食可以不加。",
    aliases: ["日料", "三文鱼", "豆腐", "沙拉"],
    goalFit: ["fat_loss", "weight_loss", "health", "muscle"],
    lightOnly: true
  },
  {
    id: "cat-steak-tomahawk-share",
    brand: "西餐厅",
    title: "战斧牛排分享小份 + 沙拉",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["战斧牛排分享小份", "蔬菜沙拉", "烤蘑菇"],
    macros: { protein: 60, carbs: 18, fat: 46, calories: 730, fiber: 5 },
    note: "战斧牛排适合多人分食，自己吃时控制小份。",
    caution: "脂肪偏高，不适合减重日常餐。",
    aliases: ["牛排", "战斧", "steak", "沙拉"],
    goalFit: ["muscle", "health"]
  },
  {
    id: "cat-steak-sirloin-eggs",
    brand: "西式简餐",
    title: "西冷牛排 + 鸡蛋 + 蔬菜",
    scene: "light_meal",
    foodType: "牛排",
    category: "meal",
    items: ["西冷牛排 150g", "鸡蛋 1 个", "烤蔬菜"],
    macros: { protein: 54, carbs: 16, fat: 30, calories: 560, fiber: 5 },
    note: "低碳日想吃牛排时，这个组合更直接。",
    aliases: ["牛排", "西冷", "鸡蛋", "steak"],
    goalFit: ["fat_loss", "health", "muscle"]
  }
];

export const catalogRecommendations: Recommendation[] = foodCatalog.map(catalogItemToRecommendation);

export function catalogItemToRecommendation(item: FoodCatalogItem): Recommendation {
  return {
    id: `catalog-${item.id}`,
    title: item.title,
    brand: item.brand,
    category: item.category,
    items: item.items,
    macros: item.macros,
    note: `${item.note}（知识库估算，可按实际份量微调。）`,
    caution: item.caution
  };
}

export function getFoodCatalogPromptSummary({
  goal,
  lightOnly,
  limit = 48
}: {
  goal?: string;
  lightOnly?: boolean;
  limit?: number;
}) {
  const items = foodCatalog
    .filter((item) => !lightOnly || item.lightOnly || item.category !== "meal")
    .filter((item) => !goal || item.goalFit.includes(goal as FoodCatalogItem["goalFit"][number]) || item.goalFit.includes("health"))
    .slice(0, limit);

  return items
    .map((item) => {
      const macros = `P${item.macros.protein}/C${item.macros.carbs}/F${item.macros.fat}/K${item.macros.calories}/纤维${item.macros.fiber}`;
      return `${item.brand}｜${item.title}｜${item.category}｜${item.foodType}｜${item.items.join("+")}｜${macros}｜${item.note}`;
    })
    .join("\n");
}
